package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class default_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_005fvar_005fitems_005fend_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_005fvalue_005fmaxFractionDigits_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_005fvar_005fitems_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_005fvalue_005fmaxFractionDigits_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_005fvar_005fitems_005fend_005fbegin.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_005fvalue_005fmaxFractionDigits_005fnobody.release();
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("   <title>拍拍贷官网_中国领先互联网金融P2P网贷平台_网络贷款_投资理财</title>\r\n");
      out.write("    <meta name=\"description\" content=\"拍拍贷-中国领先互联网金融P2P网贷平台 提供网络贷款，投资理财 小额贷款,短期贷款,个人贷款,无抵押贷款服务 拍拍贷理财借贷投资，获得高年收益率回报，超低门槛，超高收益\" />\r\n");
      out.write("    <meta name=\"keywords\" content=\"拍拍贷,拍拍贷官网,P2P网贷,互联网金融,网络贷款,投资理财\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./ppd_default_files/basic.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./ppd_default_files/layout.css\" />\r\n");
      out.write("    <link href=\"./ppd_default_files/validation-min.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"./ppd_default_files/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("    <script src=\"./ppd_default_files/newRefer.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        var _bdhmProtocol = ((\"https:\" == document.location.protocol) ? \" https://\" : \" http://\");\r\n");
      out.write("        document.write(unescape(\"%3Cscript src='\" + _bdhmProtocol + \"hm.baidu.com/h.js%3Faab1030ecb68cd7b5c613bd7a5127a40' type='text/javascript'%3E%3C/script%3E\"));\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./ppd_default_files/index.css\" />\r\n");
      out.write("    <script>\r\n");
      out.write("        var userAgentInfo = navigator.userAgent;\r\n");
      out.write("        var Agents = new Array(\"Android\", \"iPhone\", \"SymbianOS\", \"Windows Phone\", \"iPod\");\r\n");
      out.write("        var flag = true;\r\n");
      out.write("        var lolhref = window.location.href;\r\n");
      out.write("        \r\n");
      out.write("        if (lolhref.indexOf(\"fromwap\") != -1) {\r\n");
      out.write("            if (getCookie(\"wapvisted\") == null) {\r\n");
      out.write("                addCookie('wapvisted', '1', 365,'/', 'www.ppdai.com');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        if (getCookie(\"wapvisted\") == null) {\r\n");
      out.write("            for (var v = 0; v < Agents.length; v++) {\r\n");
      out.write("                if (userAgentInfo.indexOf(Agents[v]) > 0) {\r\n");
      out.write("                    window.location.href = 'http://wap.ppdai.com/';\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        //获取cookie\r\n");
      out.write("        function getCookie(name) {\r\n");
      out.write("            var arr, reg = new RegExp(\"(^| )\" + name + \"=([^;]*)(;|$)\");\r\n");
      out.write("            if (arr = document.cookie.match(reg))\r\n");
      out.write("\r\n");
      out.write("                return unescape(arr[2]);\r\n");
      out.write("            else\r\n");
      out.write("                return null;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        //添加cookie\r\n");
      out.write("        function addCookie(name, value, expires, path, domain) {\r\n");
      out.write("            var str = name + \"=\" + escape(value);\r\n");
      out.write("            if (expires != \"\") {\r\n");
      out.write("                var date = new Date();\r\n");
      out.write("                date.setTime(date.getTime() + expires * 24 * 3600 * 1000);//expires单位为天\r\n");
      out.write("                str += \";expires=\" + date.toGMTString();\r\n");
      out.write("            }\r\n");
      out.write("            if (path != \"\") {\r\n");
      out.write("                str += \";path=\" + path;//指定可访问cookie的目录\r\n");
      out.write("            }\r\n");
      out.write("            if (domain != \"\") {\r\n");
      out.write("                str += \";domain=\" + domain;//指定可访问cookie的域\r\n");
      out.write("            }\r\n");
      out.write("            document.cookie = str;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"top PPD_header_nav\">\r\n");
      out.write("         <div class=\"top_inner w1188center clearfix PPD_login_status\"><div style=\"width: 1188px;\" class=\"top_inner w1000center clearfix\"><div class=\"mobileappdownload\"><a href=\"http://www.ppdai.com/landingappdownload.html\" target=\"_blank\">下载手机客户端</a></div><ul class=\"top_toolNav\"><li><a href=\"javascript:switchUI(2013);\">切换旧版</a></li><li class=\"w68\"><a href=\"login.jsp\">登录</a></li><li class=\"w68 mr15\"><a href=\"zhuce.jsp\">注册</a></li><li class=\"hasStatusArrow\"><a href=\"http://help.ppdai.com\" class=\"fz14\">帮助</a><em class=\"statusArrow statusArrowDown\"></em><div class=\"subContent\"><a href=\"http://www.ppdai.com/consult\">客服</a><a href=\"http://group.ppdai.com\">论坛</a></div></li></ul></div></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"mainNav\">\r\n");
      out.write("        <div class=\"mainNav_inner w1188center clearfix\">\r\n");
      out.write("            <h1 class=\"logo\">\r\n");
      out.write("                <a href=\"/PPD\">\r\n");
      out.write("                    <img src=\"./ppd_default_files/logo.png\" alt=\"\" /></a>\r\n");
      out.write("            </h1>\r\n");
      out.write("            <ul id=\"tabIcon\">\r\n");
      out.write("                <li class=\"hasSubMenu\">\r\n");
      out.write("                    <a href=\"loan/loanfindall\" category=\"Lend\">我要投资</a>\r\n");
      out.write("                    <div class=\"subMenu\">\r\n");
      out.write("                        <a href=\"loan/loanfindall\">我要投资</a>\r\n");
      out.write("                        <a href=\"howtolend.jsp\">如何投资</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"hasSubMenu\">\r\n");
      out.write("                    <a href=\"woyaojiekuan.jsp\" category=\"Borrow\">我要借款</a>\r\n");
      out.write("                    <div class=\"subMenu\">\r\n");
      out.write("                        <a href=\"woyaojiekuan.jsp\">我要借款</a>\r\n");
      out.write("                        <a href=\"howtoborrow.jsp\">如何借款</a>\r\n");
      out.write("                        <a href=\"lixijisuanqi.jsp\">利息计算器</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"hasSubMenu\"><a href=\"myAccount-baccount\" category=\"Account\">我的账户</a>\r\n");
      out.write("                    <div class=\"subMenu\">\r\n");
      out.write("                        <a href=\"myAccount-baccount\">借款账户</a>\r\n");
      out.write("                        <a href=\"myAccount-laccount\">投资账户</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"hasSubMenu\"><a href=\"/help/aboutus\" category=\"About\">关于拍拍贷</a>\r\n");
      out.write("                    <div class=\"subMenu\">\r\n");
      out.write("                        <a href=\"/help/aboutus\">关于我们</a>\r\n");
      out.write("                        <a href=\"/help/howworks\">工作原理</a>\r\n");
      out.write("                        <a href=\"/help/fees\">资费说明</a>\r\n");
      out.write("                        <a href=\"/job\">招贤纳士</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("<!-- 顶部占位符-->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"slideBanner\">\r\n");
      out.write("\t\t<div id=\"kinMaxShow\">\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("    <div>\r\n");
      out.write("          <a target=\"_blank\" title=\"拍钱包:新年大回馈\" href=\"http://www.ppdai.com/event/huodong4.html?a=sy\"><img src=\"./ppd_default_files/c5835e24-c6c4-4340-95c2-04606e890375.jpg\" /></a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div>\r\n");
      out.write("          <a target=\"_blank\" title=\"拍拍贷理财app,让投资尽在掌握\" href=\"http://www.ppdai.com/landingappdownload.html\"><img src=\"./ppd_default_files/62583339-bffc-4028-b524-c0f9b9e206d8.jpg\" /></a>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("    <div>\r\n");
      out.write("          <a title=\"触手可及的金融\"><img src=\"./ppd_default_files/8162a4a9-8bbb-4807-b35f-fd65a33db12b.jpg\" /></a>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("    <div>\r\n");
      out.write("        <a target=\"_blank\" title=\"彩虹计划,7种期限任你选\" href=\"http://www.ppdai.com/product/plan/rainbow\"><img src=\"./ppd_default_files/3ddea793-b6f0-40f5-ba5f-1659ec16df53.jpg\" /></a>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("    <div>\r\n");
      out.write("        <a title=\"拍拍贷微信\"><img src=\"./ppd_default_files/banner_wxcode.jpg\" /></a>\r\n");
      out.write("    </div>\r\n");
      out.write("      \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"bannerRight\">\r\n");
      out.write("    <div class=\"inner\">\r\n");
      out.write("        <div class=\"title\">\r\n");
      out.write("            <h3>\r\n");
      out.write("                简单、快速、借得到！\r\n");
      out.write("            </h3>\r\n");
      out.write("            <p>\r\n");
      out.write("                  <!--人数--><strong xid=\"0\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${countUsers}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("</strong>人发现拍拍贷\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("            <h3>\r\n");
      out.write("                拍拍贷历史年化收益率\r\n");
      out.write("            </h3>\r\n");
      out.write("            <p>\r\n");
      out.write("                平均<strong>12%-20%</strong>\r\n");
      out.write("            </p>\r\n");
      out.write("        </div><a href=\"/lend\" class=\"bannerA pos1\">我要投资</a><a href=\"/borrow\" class=\"bannerA pos2\">我要借款</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<div class=\"index_propaganda\">\r\n");
      out.write("    <div class=\"wrap clearfix\">\r\n");
      out.write("        <div class=\"index_propaganda_left\">\r\n");
      out.write("            <div class=\"part\" style=\"width: 136px\">\r\n");
      out.write("                <img src=\"./ppd_default_files/safe.png\" alt=\"\" />\r\n");
      out.write("                <h3>安全</h3>\r\n");
      out.write("                <p>风险备用金计划</p>\r\n");
      out.write("                <p>安全有保障</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"part\" style=\"width: 136px\">\r\n");
      out.write("                <img src=\"./ppd_default_files/professional.png\" alt=\"\" />\r\n");
      out.write("                <h3>专业</h3>\r\n");
      out.write("                <p>规范操作：七年历史</p>\r\n");
      out.write("                <p>最多用户的选择</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"part\" style=\"width: 145px;\">\r\n");
      out.write("                <img src=\"./ppd_default_files/tuhao.png\" alt=\"\" />\r\n");
      out.write("                <h3>有钱</h3>\r\n");
      out.write("                <p>无论是资金，还是收益</p>\r\n");
      out.write("                <p>拍拍贷总能让你有钱</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("            <!--数据统计-->\r\n");
      out.write("        <div class=\"index_propaganda_right\">\r\n");
      out.write("    <div class=\"inner\">\r\n");
      out.write("        <div class=\"tag pos1\">\r\n");
      out.write("            至今\r\n");
      out.write("        </div>\r\n");
      out.write("        <h3>\r\n");
      out.write("            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${countUsers}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("        </h3>\r\n");
      out.write("        <p>\r\n");
      out.write("            人发现并注册拍拍贷\r\n");
      out.write("        </p>\r\n");
      out.write("        <div class=\"tag pos2\">\r\n");
      out.write("            上月\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"info\">\r\n");
      out.write("            <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${countLoan}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("</strong>人次借款\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"info\">\r\n");
      out.write("        \t<strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${countInvest}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("</strong>人次投资\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"wrap clearfix\">\r\n");
      out.write("        <div class=\"index_propaganda_left bgno1\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"index_propaganda_right\" style=\"margin-top: 23px;\">\r\n");
      out.write("            <h4>谁在报道拍拍贷 <a href=\"/help/mediareports\">more&gt;</a></h4>\r\n");
      out.write("            <a href=\"/help/mediareports\" class=\"media\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"index_info\">\r\n");
      out.write("    <div class=\"wrap clearfix\">\r\n");
      out.write("        <div class=\"infoLeft\">\r\n");
      out.write("            <div class=\"tabNav\">\r\n");
      out.write("                <ul class=\"clearfix\">\r\n");
      out.write("                    <li class=\"first current\">投资信息</li>\r\n");
      out.write("                    <li class=\"second\">借款信息</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"tabContent\">\r\n");
      out.write("                <!--投资信息-->\r\n");
      out.write("                <div class=\"borrowInfo\" style=\"display: block;\">\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("                    <a href=\"/lend\" class=\"indexTabVierMore\">查看更多投资信息&gt;</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!--借款信息-->\r\n");
      out.write("                <div class=\"lendInfo\" style=\"display: none;\">\r\n");
      out.write("                    <div class=\"part\">\r\n");
      out.write("                        <h3 class=\"title blue\">普通贷款标 — 适用工薪族\r\n");
      out.write("                        </h3>\r\n");
      out.write("                        <div class=\"lendInfo_detailInfo clearfix\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>21~55周岁中国大陆公民</li>\r\n");
      out.write("                                <li>需有稳定收入来源证明</li>\r\n");
      out.write("                                <li>最快1天到账</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <a href=\"/borrow/createlist/1\" class=\"quickApply\">立即申请</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"part\">\r\n");
      out.write("                        <h3 class=\"title yellow\">网商用户标 — 为网商卖家进货、参加活动以及资金周转而设\r\n");
      out.write("                        </h3>\r\n");
      out.write("                        <div class=\"lendInfo_detailInfo clearfix\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>21~55周岁中国大陆公民</li>\r\n");
      out.write("                                <li>需通过网商认证</li>\r\n");
      out.write("                                <li>借款额度根据店铺经营情况调整，最高可达50万</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <a href=\"/borrow/createlist/2\" class=\"quickApply\">立即申请</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"part\">\r\n");
      out.write("                        <h3 class=\"title red\">莘莘学子标 — 适用大学生\r\n");
      out.write("                        </h3>\r\n");
      out.write("                        <div class=\"lendInfo_detailInfo clearfix\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>19~25周岁中国大陆公民</li>\r\n");
      out.write("                                <li>需通过学籍和视频认证</li>\r\n");
      out.write("                                <li>首次申请全额还款后拍拍贷全额退还成交服务费</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <a href=\"/borrow/createlist/7\" class=\"quickApply\">立即申请</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"/borrow\" class=\"indexTabVierMore\">查看更多借款信息&gt;</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"infoRight\">\r\n");
      out.write("            <div class=\"part\">\r\n");
      out.write("                <h4>最新公告\t<a href=\"/help/announcementlist\">more&gt;</a></h4>\r\n");
      out.write("                <script type=\"text/javascript\" src=\"./ppd_default_files/newnotice.js\"> </script>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"part\">\r\n");
      out.write("                <h4>公司资讯\t<a href=\"/help2/mediaReports\">more&gt;</a></h4>\r\n");
      out.write("                <script type=\"text/javascript\" src=\"./ppd_default_files/newmediareport.js\"> </script>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"part pos\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <a href=\"/borrow/interestcalculate\"><span></span>利息计算器</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"index_case w1188center clearfix\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"index_case_case\">\r\n");
      out.write("        <div class=\"img\">\r\n");
      out.write("            <a href=\"http://www.ppdai.com/lend/12\">\r\n");
      out.write("                <img src=\"./ppd_default_files/indexcase1.jpg\" alt=\"\" /></a>\r\n");
      out.write("            <div class=\"text\">\r\n");
      out.write("                <p><a href=\"http://www.ppdai.com/lend/12\">我算是拍拍贷的老用户。他们这里理念很好，就是教育大家分散风险，多投点标，每标的金额小一点。如果你确实这么操作了，公司会提供本金保障。我现在累计投了快2000笔，收益13%左右，还不是最高的，我会继续投下去。</a></p>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"explain\">\r\n");
      out.write("            <h3>投资信用标<br />\r\n");
      out.write("                眼光决定收益！</h3>\r\n");
      out.write("            <p>\r\n");
      out.write("                享受每天自助投资乐趣<br />\r\n");
      out.write("                年化收益可达16%<br />\r\n");
      out.write("                每月还本付息，<br />\r\n");
      out.write("                超低门槛，最低50元可体验\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"index_case_case\">\r\n");
      out.write("        <div class=\"img\">\r\n");
      out.write("            <a href=\"http://www.ppdai.com/product/list\">\r\n");
      out.write("                <img src=\"./ppd_default_files/indexcase2.jpg\" alt=\"\" /></a>\r\n");
      out.write("            <div class=\"text\">\r\n");
      out.write("                <p><a href=\"http://www.ppdai.com/product/list\">之前听朋友介绍拍拍贷，但是我平时工作比较忙，没时间选标。最近推出的这种“彩虹计划”就很不错，一次性投资，投资资金参与本金保障计划，预期年化收益率最高可达12%。我已经抢购了几期，现在就等着到期来收钱了。</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"explain\">\r\n");
      out.write("            <h3>彩虹计划<br />\r\n");
      out.write("                省心省力，坐享其成！</h3>\r\n");
      out.write("            <p>\r\n");
      out.write("                省心省力，坐享其成！一键轻松购买，省去每天选标烦恼<br />\r\n");
      out.write("                预期年化收益率最高12%，稳定收益<br />\r\n");
      out.write("                7种期限选择，投资资金参与本金保障计划<br />\r\n");
      out.write("                低门槛，1000元起购\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"index_case_weixin\">\r\n");
      out.write("        <div class=\"img\">\r\n");
      out.write("\r\n");
      out.write("            <img src=\"./ppd_default_files/indexcase3.jpg\" alt=\"\" />\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"explain\">\r\n");
      out.write("            <h3>扫描关注<br />\r\n");
      out.write("                拍拍贷微信</h3>\r\n");
      out.write("            <p>年化8% + 稳定收益</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 底部占位符-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"clear\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("            <div class=\"footer_inner clearfix\">\r\n");
      out.write("                <div class=\"footer_footerNav\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>关于拍拍贷</dt>\r\n");
      out.write("                        <dd><a href=\"http://www.ppdai.com/help/pioneer\">拍拍贷团队</a></dd>\r\n");
      out.write("                        <dd><a href=\"http://www.ppdai.com/help/mediaReports\">媒体报道</a></dd>\r\n");
      out.write("                        <dd><a href=\"http://www.ppdai.com/job\">招贤纳士</a></dd>\r\n");
      out.write("                        <dd><a href=\"http://www.ppdai.com/help/contactus\">联系我们</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>业务信息</dt>\r\n");
      out.write("                        <dd><a href=\"http://www.ppdai.com/borrow\">我要借款</a></dd>\r\n");
      out.write("                        <dd><a href=\"http://www.ppdai.com/lend/12\">我要投资</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>诚信保障</dt>\r\n");
      out.write("                        <dd><a href=\"http://www.ppdai.com/help/law\">法律政策</a></dd>\r\n");
      out.write("                        <dd><a href=\"http://www.ppdai.com/help/principalprotection\">本金保障</a></dd>\r\n");
      out.write("                        <dd><a href=\"http://www.ppdai.com/help/howworks\">工作原理</a></dd>\r\n");
      out.write("                        <dd><a href=\"http://www.ppdai.com/help/fees\">资费说明</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt>客户服务</dt>\r\n");
      out.write("                        <dd><a href=\"http://weibo.com/ppdai07\">新浪微博</a></dd>\r\n");
      out.write("                        <dd><a href=\"http://e.t.qq.com/ppdai_com\">腾讯微博</a></dd>\r\n");
      out.write("                        <dd><a href=\"javascript:;\">微信</a></dd>\r\n");
      out.write("                        <dd style=\"color: #666;\">400-184-8888</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer_footerInfo\">\r\n");
      out.write("                    <a href=\"###\">\r\n");
      out.write("                        <img src=\"./ppd_default_files/footerlogo.png\" alt=\"\" /></a>\r\n");
      out.write("                    <p>拍拍贷成立于2007年6月，是国内第一家由工商部门特批获得“金融信息服务”资质，从而得到政府认可的平台。拍拍贷致力于搭建一个安全、高效、诚信、透明的互联网金融平台，规范个人借贷行为，改善借款人状态，同时拓宽借出者投资渠道。</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        <div class=\"footer_footerBottom\">\r\n");
      out.write("            <ul class=\"footer_footerBottomNav clearfix\">\r\n");
      out.write("                <li><span class=\"webindex\"></span><a href=\"/\">网站首页</a>|</li>\r\n");
      out.write("                <li><span class=\"aboutus\"></span><a href=\"/help/aboutus\">关于我们</a>|</li>\r\n");
      out.write("                <li><span class=\"mapsite\"></span><a href=\"/home/sitemap\">网站地图</a>|</li>\r\n");
      out.write("                <li><span class=\"webservice\"></span><a href=\"/consult\">客服中心</a>|</li>\r\n");
      out.write("                <li class=\"nomr\"><span class=\"onlneserve\"></span><a href=\"http://wpa.b.qq.com/cgi/wpa.php?ln=1&key=XzgwMDAyNzUzNV8xODAzNjBfODAwMDI3NTM1XzJf\" target=\"_blank\">在线咨询</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <p>Copyright Reserved 2007-2015©拍拍贷（www.ppdai.com）&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;沪ICP备05063398号&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;上海拍拍贷金融信息服务有限公司</p>\r\n");
      out.write("<div style=\"padding-bottom:0px;\" class=\"f_link_nav\">\r\n");
      out.write("    <div class=\"float_l l-t\">\r\n");
      out.write("        网站链接：\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"float_l r-t\">\r\n");
      out.write("        <meta name=\"baidu-site-verification\" content=\"nweZ85zRaR\" />\r\n");
      out.write("        <a href=\"http://www.ppdai.com/zixun/zt_paipaidaitouzi\" target=\"_blank\">拍拍贷怎么样</a><a href=\"http://www.ppdai.com/daikuan/wangsbltzk\" target=\"_blank\">透支卡</a><a href=\"http://xueshengdaikuan.ppdai.com\" target=\"_blank\">大学生贷款</a><a href=\"http://xiaoedaikdk.ppdai.com\" target=\"_blank\">小额贷款</a><a href=\"http://touzilcchanp.ppdai.com\" target=\"_blank\">投资理财</a> \r\n");
      out.write("        <div style=\"float:left\" id=\"show_tab1\" onclick=\"$(&#39;#unshow_tab1&#39;).show();$(&#39;#show_tab1&#39;).hide();\">\r\n");
      out.write("            <a href=\"javascript:void(0);\">更多...</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"height:1px\" class=\"float_l l-t\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"display:none\" id=\"unshow_tab1\" class=\"float_l r-t\">\r\n");
      out.write("        <a href=\"http://www.ppdai.com/zixun/gupiaormjczs\" target=\"_blank\">股票知识</a> <a href=\"http://www.ppdai.com/zixun/zhengquangs\" target=\"_blank\">证券公司</a><a href=\"http://www.ppdai.com/zixun/jinrongzhishi\" target=\"_blank\">金融知识</a><a href=\"http://www.ppdai.com/zixun/gupiaormjczs\" target=\"_blank\">股票知识</a><a href=\"http://www.ppdai.com/zixun/qihuogongsi\" target=\"_blank\">期货公司</a><a href=\"http://www.ppdai.com/zixun/daikuanzhishi\" target=\"_blank\">贷款知识</a><a href=\"http://www.ppdai.com/zixun/waihuizhis\" target=\"_blank\">外汇知识</a><a href=\"http://www.ppdai.com/zixun/rongzifangshi\" target=\"_blank\">融资方式</a><a href=\"http://www.ppdai.com/daikuan/iphone6fqfk/page_1\" target=\"_blank\">iphone6分期付款</a><a href=\"http://www.ppdai.com/daikuan/xiaoedaikuan\" target=\"_blank\">急需小额贷款</a><a href=\"http://www.ppdai.com/daikuan/sqtouzhika\" target=\"_blank\">透支卡</a><a href=\"http://www.ppdai.com/zixun/zt_paipaidaitouzi\" target=\"_blank\">拍拍贷投资</a><a href=\"http://www.ppdai.com/daikuan/pgsjpg6\" target=\"_blank\">苹果6</a><a href=\"http://www.ppdai.com/daikuan/xpxp\" target=\"_blank\">夏普分期</a><a href=\"http://www.ppdai.com/daikuan/ddcddc\" target=\"_blank\">电动车分期</a><a href=\"http://www.ppdai.com/daikuan/hqhqi\" target=\"_blank\">宏碁分期</a><a href=\"http://www.ppdai.com/daikuan/defqde\" target=\"_blank\">戴尔分期付款</a><a href=\"http://www.ppdai.com/daikuan/jsqjsq\" target=\"_blank\">净水器分期</a><a href=\"http://www.ppdai.com/daikuan/hsfqhsbjb\" target=\"_blank\">分期付款买华硕</a><a href=\"http://www.ppdai.com/daikuan/hsfqhsbjb\" target=\"_blank\">分期付款买华硕</a><a href=\"http://www.ppdai.com/daikuan/ppdkxm\" target=\"_blank\">拍拍贷可信</a><a href=\"http://www.ppdai.com/daikuan/zijinzhouzhuan\" target=\"_blank\">资金周转</a><a href=\"http://www.ppdai.com/daikuan/qhtfqhtf\" target=\"_blank\">清华同方分期</a><a href=\"http://www.ppdai.com/daikuan/gjsydzxdkdlxt\" target=\"_blank\">助学贷款</a><a href=\"http://www.ppdai.com/daikuan/xedaikuan\" target=\"_blank\">小额贷款</a><a href=\"http://www.ppdai.com/zixun/wangdai\" target=\"_blank\">p2p网贷平台</a><a href=\"http://www.ppdai.com/zixun/licaichanpin\" target=\"_blank\">理财产品</a><a href=\"http://www.ppdai.com/daikuan/aksakskdzmy\" target=\"_blank\">奥克斯分期</a><a href=\"http://www.ppdai.com/zixun/niwodai\" target=\"_blank\">你我贷怎么样</a><a href=\"http://www.ppdai.com/daikuan/glglkd\">格力空调分期</a><a href=\"http://www.ppdai.com/daikuan/rzrzrq\">融资融券</a><a href=\"http://www.ppdai.com/daikuan/glgl\">格力分期</a><a href=\"http://www.ppdai.com/daikuan/pgfqpgdn\">苹果分期</a><a href=\"http://www.ppdai.com/daikuan/xedaikuan\" target=\"_blank\">小额贷款</a><a href=\"http://www.ppdai.com/daikuan/ppdkxm\" target=\"_blank\">拍拍贷网</a><a href=\"http://www.ppdai.com/daikuan/paipaidaiwkkm\" target=\"_blank\">拍拍贷怎么样</a><a href=\"http://www.ppdai.com/daikuan/ftftrqz\" target=\"_blank\">方太分期</a><a href=\"http://www.ppdai.com/daikuan/jsdjsdnc\" target=\"_blank\">金士顿分期</a><a href=\"http://www.ppdai.com/daikuan/jhqkqjhq\" target=\"_blank\">净化器分期</a><a href=\"http://www.ppdai.com/daikuan/zgmjjd\" target=\"_blank\">民间借贷</a><a href=\"http://www.ppdai.com/daikuan/tbfqtbxykfq\" target=\"_blank\">淘宝分期</a><a href=\"http://www.ppdai.com/daikuan/zqzxzqgb\" target=\"_blank\">中信证券</a><a href=\"http://www.ppdai.com/daikuan/defqde\" target=\"_blank\">戴尔分期</a><a href=\"http://www.ppdai.com/daikuan/lxfqlx\" target=\"_blank\">联想分期</a><a href=\"http://www.ppdai.com/daikuan/wudiyadk1\" target=\"_blank\">无抵押个人贷款</a><a href=\"http://www.ppdai.com/daikuan/xuesdaikuan\" target=\"_blank\">助学贷款</a><a href=\"http://www.ppdai.com/daikuan/wdtiyan\" target=\"_blank\">网贷体验</a><a href=\"http://www.ppdai.com/daikuan/xinyongedu\" target=\"_blank\">提升信用额度</a><a href=\"http://www.ppdai.com/daikuan/p2ptouzi\" target=\"_blank\">p2p投资理财</a><a href=\"http://www.ppdai.com/daikuan/wstouzilicai\" target=\"_blank\">网上投资理财</a><a href=\"http://www.ppdai.com/daikuan/jiyongqian\" target=\"_blank\">急用钱贷款</a><a href=\"http://www.ppdai.com/daikuan/hpfqhp\" target=\"_blank\">惠普分期</a><a href=\"http://www.ppdai.com/daikuan/gaolidgldsflbhm\" target=\"_blank\">高利贷</a><a href=\"http://www.ppdai.com/daikuan/sn4gsjsn\" target=\"_blank\">索尼手机分期</a><a href=\"http://www.ppdai.com/zixun/zaitiexian\" target=\"_blank\">再贴现率</a><a href=\"http://www.ppdai.com/daikuan/fqmcqc\" target=\"_blank\">分期买车</a><a href=\"http://www.ppdai.com/daikuan/sxsx\" target=\"_blank\">三星分期</a><a href=\"http://www.ppdai.com/daikuan/licaichanpin\" target=\"_blank\">理财产品</a><a href=\"http://wangsbltzk.ppdai.com\" target=\"_blank\">透支卡</a><a href=\"http://www.ppdai.com/daikuan/ppdrrdzenmy\" target=\"_blank\">拍拍贷和人人贷</a><a href=\"http://www.ppdai.com/daikuan/xjxj\" target=\"_blank\">希捷分期</a><a href=\"http://www.ppdai.com/daikuan/tmfqtmfqg\" target=\"_blank\">天猫分期</a><a href=\"http://www.ppdai.com/daikuan/rrdaizenmy\" target=\"_blank\">人人贷怎么样</a><a href=\"http://www.ppdai.com/zixun/yonganqihuo\" target=\"_blank\">永安期货</a><a href=\"http://www.ppdai.com/daikuan/ppdkxm\" target=\"_blank\">拍拍贷网</a><a href=\"http://www.ppdai.com/daikuan/gjkfyhzxdkxtdl/page_16\" target=\"_blank\">助学贷款</a> <a href=\"http://www.ppdai.com/daikuan/xiaofeidaikuan\" target=\"_blank\">个人消费贷款</a><a href=\"http://www.ppdai.com/daikuan/jyjydj\" target=\"_blank\">九阳豆浆机分期</a><a href=\"http://www.ppdai.com/daikuan/xueshengdaikuan\" target=\"_blank\">学生贷款</a><a href=\"http://www.ppdai.com/daikuan/glsgls\" target=\"_blank\">格兰仕分期</a> <a href=\"http://www.ppdai.com/daikuan/hmhmsj\" target=\"_blank\">红米分期</a> <a href=\"http://www.ppdai.com/daikuan/mpmacbookpro\" target=\"_blank\">macbook pro分期</a> <a href=\"http://www.ppdai.com/daikuan/mamacbookair\" target=\"_blank\">macbook air分期</a> <a href=\"http://www.ppdai.com/daikuan/idipadmini\" target=\"_blank\">ipad mini分期</a>  <a href=\"http://www.ppdai.com/daikuan/idipadair\" target=\"_blank\">ipad air分期</a>  <a href=\"http://www.ppdai.com/daikuan/trzzhxqyejtrzpt\" target=\"_blank\">小企业e家</a> <a href=\"http://www.ppdai.com/zixun/caijingmingren\" target=\"_blank\">财经名人</a>  <a href=\"http://www.ppdai.com/daikuan/thipodtouch\" target=\"_blank\">ipod touch分期</a>   <a href=\"http://www.ppdai.com/daikuan/t5ipodtouch5\" target=\"_blank\">ipod touch5分期</a>    <a href=\"http://www.ppdai.com/daikuan/lxdklxzj\" target=\"_blank\">留学贷款</a>  <a href=\"http://www.ppdai.com/daikuan/xcdkxc\" rget=\"_blank\">学车贷款</a> <a href=\"http://www.ppdai.com/daikuan/pxdkpx\" rget=\"_blank\">培训贷款</a> <a href=\"http://www.ppdai.com/daikuan/kddkkd\" rget=\"_blank\">开店贷款</a>  <a href=\"http://www.ppdai.com/daikuan/zjzzzjzz\" rget=\"_blank\">资金周转</a>  <a href=\"http://www.ppdai.com/daikuan/5siphone5sjg\" rget=\"_blank\">iph5s分期</a> <a href=\"http://www.ppdai.com/daikuan/i5iphone4s\" rget=\"_blank\">iph5分期</a> <a href=\"http://www.ppdai.com/daikuan/jieqgrksjq1000\" rget=\"_blank\">借钱</a> <a href=\"http://www.ppdai.com/daikuan/5siphone5sjg\" rget=\"_blank\">iphone5s分期</a>  <a href=\"http://www.ppdai.com/daikuan/idipad\" rget=\"_blank\">ipad分期</a> <a href=\"http://www.ppdai.com/daikuan/mkmacbook\" rget=\"_blank\">macbook分期</a>  <a href=\"http://www.ppdai.com/daikuan/jsqjsq\" rget=\"_blank\">加湿器分期</a> <a href=\"http://www.ppdai.com/daikuan/ymhymh\r\n");
      out.write("\" rget=\"_blank\">雅马哈分期</a> <a href=\"http://www.ppdai.com/daikuan/idipadmini\" rget=\"_blank\">ipad mini分期</a> <a href=\"http://jiyongmoney.ppdai.com\" target=\"_blank\">急需用钱</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div style=\"padding-bottom:0px;\" class=\"f_link_nav\">\r\n");
      out.write("    <div class=\"float_l l-t\">\r\n");
      out.write("        友情链接：\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"float_l r-t\">\r\n");
      out.write("        <a href=\"http://www.gucheng.com\" target=\"_blank\">股城网</a><a href=\"http://www.ggcj.com/\" target=\"_blank\">呱呱财经</a> <a href=\"http://finance.ifeng.com/itfinance/index.shtml\" target=\"_blank\">凤凰财经</a>  <a href=\"http://www.xiangrikui.com/\" target=\"_blank\">向日葵保险网</a> \r\n");
      out.write("        <div style=\"float:left\" id=\"show_tab\" onclick=\"$(&#39;#unshow_tab&#39;).show();$(&#39;#show_tab&#39;).hide();\">\r\n");
      out.write("            <a href=\"javascript:void(0);\">更多...</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"height:1px\" class=\"float_l l-t\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"display:none\" id=\"unshow_tab\" class=\"float_l r-t\">\r\n");
      out.write("         <a href=\"http://www.xftz.cn\" target=\"_blank\">幸福黄金网</a><a href=\"http://www.jfinfo.com\" target=\"_blank\">丰华财经</a><a href=\"http://www.anxin.com\" target=\"_blank\">安心贷</a><a href=\"http://value500.com/\" target=\"_blank\">投资理财导航</a><a href=\"http://www.rongzicn.com\" target=\"_blank\">融资网</a><a href=\"http://www.dajiabao.com\" target=\"_blank\">大家保</a><a href=\"http://www.p2peye.com\" rel=\"nofollow\" target=\"_blank\">网贷天眼</a><a href=\"http://www.caiguu.com/licai/\" target=\"_blank\">财股网理财</a><a href=\"http://www.7878.com\" target=\"_blank\">资本魔方</a><a href=\"http://www.xs9999.com/\" target=\"_blank\">贵金属投资</a><a href=\"http://www.baobao18.com\" target=\"_blank\">保保网</a><a href=\"http://licai.cofool.com/\" target=\"_blank\">同城理财</a><a href=\"http://www.csai.cn/\" target=\"_blank\">理财产品</a><a href=\"http://www.wm927.com\" target=\"_blank\">智通财经网</a><a href=\"http://www.diyizby.com\" target=\"_blank\"> 纸白银</a><a href=\"http://www.wanyiwang.com\" target=\"_blank\">保险资料</a><a href=\"http://www.fundfund.cn\" target=\"_blank\">天天基金</a><a href=\"http://www.miaogu.com\" target=\"_blank\">瞄股网</a><a href=\"http://loans.cardbaobao.com\" target=\"_blank\">小额贷款</a><a href=\"http://www.tou18.cn \" target=\"_blank\">股票行情</a><a href=\"http://www.andaike.com\" target=\"_blank\">安贷客贷款</a><a href=\"http://fx.godsignal.com\" target=\"_blank\">外汇网</a><a href=\"http://www.laohucaijing.com\" target=\"_blank\">环球老虎财经</a><a href=\"http://beijing.rong360.com\" target=\"_blank\">北京贷款</a><a href=\"http://www.henanjinrong.com/\" target=\"_blank\">河南金融网</a><a href=\"http://chexian.qc188.com\" target=\"_blank\"> 汽车保险</a><a href=\"http://news.51zjxm.com/\" target=\"_blank\">51资金项目网</a><a href=\"http://www.qianzhan.com/qzdata/\" target=\"_blank\">行业数据</a><a href=\"http://www.gpcxw.com\" target=\"_blank\">爱股网</a><a href=\"http://www.dyxtw.com\" target=\"_blank\">信托产品</a><a href=\"http://money.laoqianzhuang.com\" target=\"_blank\">投资理财</a><a href=\"http://www.guijinshu.com\" target=\"_blank\">贵金属</a><a href=\"http://www.roadoor.com\" target=\"_blank\">贷款</a><a href=\"http://www.zhijinwang.com\">中国纸金网</a><a href=\"http://www.silver.org.cn\" target=\"_blank\">白银价格</a><a href=\"http://bbs.wacai.com/portal.php\" target=\"_blank\">挖财社区</a><a href=\"http://hk.szhk.com/\" target=\"_blank\">香港购物</a><a href=\"http://www.ppdai.com/help/link\" target=\"_blank\">&gt;&gt;更多链接</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div><!--友情链接-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./ppd_default_files/jquery.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script src=\"./ppd_default_files/init.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script src=\"./ppd_default_files/servicestack-min.js\"></script>\r\n");
      out.write("    <script src=\"./ppd_default_files/jquery.cookie.js\"></script>\r\n");
      out.write("    <script src=\"./ppd_default_files/status?v=2014\" type=\"text/javascript\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("        $(\".my-f-l-list li a.on\").closest(\".my-f-l-list\").prev(\".my-f-l-nav\").addClass(\"my-f-l-nav-sd\");\r\n");
      out.write("        try {\r\n");
      out.write("            $(\"#tabIcon a[category='\" + breadcrumbCategory + \"']\").addClass(\"tabon\");\r\n");
      out.write("        } catch (e) {\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"./ppd_default_files/jquery.kinMaxShow-1.0.min.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script src=\"./ppd_default_files/index.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Tag Manager -->\r\n");
      out.write("    <noscript>\r\n");
      out.write("        <iframe src=\"//www.googletagmanager.com/ns.html?id=GTM-PVQ5D8\"\r\n");
      out.write("            height=\"0\" width=\"0\" style=\"display: none; visibility: hidden\"></iframe>\r\n");
      out.write("    </noscript>\r\n");
      out.write("    <script>(function (w, d, s, l, i) {\r\n");
      out.write("    w[l] = w[l] || []; w[l].push({\r\n");
      out.write("        'gtm.start':\r\n");
      out.write("            new Date().getTime(), event: 'gtm.js'\r\n");
      out.write("    }); var f = d.getElementsByTagName(s)[0],\r\n");
      out.write("            j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =\r\n");
      out.write("                '//www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);\r\n");
      out.write("})(window, document, 'script', 'dataLayer', 'GTM-PVQ5D8');</script>\r\n");
      out.write("    <!-- End Google Tag Manager -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(PageContext _jspx_page_context)
          throws Throwable {
    PageContext pageContext = _jspx_page_context;
    JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_005fvar_005fitems_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /default.jsp(243,17) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/default.jsp(243,17) '${loanList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${loanList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /default.jsp(243,17) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("loan");
    // /default.jsp(243,17) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setBegin(0);
    // /default.jsp(243,17) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setEnd(2);
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                \t\t<div class=\"part\">\r\n");
          out.write("                            <div class=\"borrowInfo_title clearfix\">\r\n");
          out.write("                                <div class=\"sum clearfix\"><i></i><span>剩余金额：&#165;");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loan.loanmoney-loan.raise}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
          out.write("</span></div>\r\n");
          out.write("                                <div class=\"name clearfix\"><i></i><span></span></div>\r\n");
          out.write("                            </div>\r\n");
          out.write("                            <div class=\"borrowInfo_detail clearfix\">\r\n");
          out.write("                                <div class=\"borrowInfo_detail_left\">\r\n");
          out.write("                                    \r\n");
          out.write("                                    \r\n");
          out.write("                                    <a href=\"http://help.ppdai.com/Home/List/12\" target=\"_blank\"><i class=\"creditRating AA\"></i></a>\r\n");
          out.write("                                    <a href=\"loan/findLoanById?loanid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loan.loanid}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
          out.write("\" class=\"lendTitle ell\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loan.title}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
          out.write("</a>\r\n");
          out.write("                                    <p>\r\n");
          out.write("                                        <span>借款金额：</span>\r\n");
          out.write("                                        <strong>&#165;");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loan.loanmoney}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
          out.write("</strong>\r\n");
          out.write("                                        <span>年利率：</span>\r\n");
          out.write("                                        <strong>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loan.rate*100}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
          out.write("<em>%</em></strong>\r\n");
          out.write("                                        <span>借款期限：</span>\r\n");
          out.write("                                        <strong class=\"nomr\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loan.loantime}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
          out.write("<em>个月</em></strong>\r\n");
          out.write("                                    </p>\r\n");
          out.write("                                </div>\r\n");
          out.write("                                <div class=\"borrowInfo_detail_right\">\r\n");
          out.write("                                    <div class=\"borrowInfo_detail_right_percentInfo clearfix\">\r\n");
          out.write("                                        <div class=\"borrowInfo_detail_right_percentInfo_percent\">\r\n");
          out.write("                                            <div class=\"inner\" style=\"width:");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loan.raise*100/loan.loanmoney}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
          out.write("%\"></div>\r\n");
          out.write("                                        </div>\r\n");
          out.write("                                        <span>\r\n");
          out.write("                                        \t");
          if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("%\r\n");
          out.write("                                        </span>\r\n");
          out.write("                                    </div>\r\n");
          out.write("                                    <a href=\"loan/findLoanById?loanid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loan.loanid}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
          out.write("\" class=\"lendBtn\">马上投标</a>\r\n");
          out.write("                                </div>\r\n");
          out.write("                            </div>\r\n");
          out.write("                        </div>\r\n");
          out.write("                \t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_005fvar_005fitems_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws Throwable {
    PageContext pageContext = _jspx_page_context;
    JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_005fvalue_005fmaxFractionDigits_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /default.jsp(270,41) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loan.raise*100/loan.loanmoney}", java.lang.Object.class, (PageContext)_jspx_page_context, null, false));
    // /default.jsp(270,41) name = maxFractionDigits type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f0.setMaxFractionDigits(2);
    int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
    if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_005fvalue_005fmaxFractionDigits_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_005fvalue_005fmaxFractionDigits_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
    return false;
  }
}
