package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class my_005frecharge_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("     <title>充值 - 拍拍贷-中国首家，最大、最多人使用的互联网金融P2P网络借贷平台。提供小额贷款,短期贷款,个人贷款,自定利率,借期灵活。您还可以成为借出人理财投资,超低门槛，获得高年收益率回报</title>\r\n");
      out.write("    <meta name=\"description\" content=\"拍拍贷，中国首家，最大、最多人使用的互联网金融P2P(人人贷)网络借贷平台。提供小额贷款,短期贷款,个人贷款,抵押,无抵押贷款服务。利率自定,借期灵活。您还可以成为借出人理财借贷投资，获得高年收益率回报，超低门槛，超高收益。作为可信赖的投融资,理财,贷款,信贷平台,拍拍贷助您财富实现增值\" />\r\n");
      out.write("    <meta name=\"keywords\" content=\"网络贷款,民间借贷,小额贷款,无抵押贷款,信用贷款,网络借贷,借贷平台,拍拍贷,人人贷,投资理财,个人理财,p2p贷款,贷款,互联网金融,投融资\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./jsp/ppd_recharge_files/basic.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./jsp/ppd_recharge_files/layout.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./jsp/ppd_recharge_files/index.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./jsp/ppd_recharge_files/account_old.css\" />\r\n");
      out.write("    <link href=\"./jsp/ppd_recharge_files/validation-min.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <script src=\"./jsp/ppd_recharge_files/jquery-1.js\"></script>\r\n");
      out.write("    <script src=\"./jsp/ppd_recharge_files/jquery-migrate-1.js\"></script>\r\n");
      out.write("    <script src=\"./jsp/ppd_recharge_files/jquery.kinMaxShow-1.0.min.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script src=\"./jsp/ppd_recharge_files/init.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script src=\"./jsp/ppd_recharge_files/servicestack-min.js\"></script>\r\n");
      out.write("    <script src=\"./jsp/ppd_recharge_files/bootstrap.js\"></script>\r\n");
      out.write("    <script src=\"./jsp/ppd_recharge_files/jquery.cookie.js\"></script>\r\n");
      out.write("    <script src=\"./jsp/ppd_recharge_files/newRefer.js\"></script>\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"./jsp/ppd_recharge_files/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"top PPD_header_nav\">\r\n");
      out.write("        <div class=\"PPD_login_status\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     <!--头部开始-->\r\n");
      out.write("    <div class=\"mainNav\">\r\n");
      out.write("        <div class=\"mainNav_inner clearfix w1000center\">\r\n");
      out.write("            <h1 class=\"logo\">\r\n");
      out.write("                <a href=\"http://www.ppdai.com/\"><img src=\"./jsp/ppd_recharge_files/logo.png\" alt=\"\" /></a>\r\n");
      out.write("            </h1>\r\n");
      out.write("            <ul id=\"tabIcon\">\r\n");
      out.write("                <li class=\"hasSubMenu\">\r\n");
      out.write("                    <a href=\"http://www.ppdai.com/lend\"  category=\"Lend\">我要投资</a>\r\n");
      out.write("                    <div class=\"subMenu\">\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/lend\">我要投资</a>\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/product/plan/rainbow\">彩虹计划</a>\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/debtdeal/AlldebtList/DebtList\">债权交易</a>\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/howtolend\">如何投资</a>\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/help/principalprotection\">本金保障</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"hasSubMenu\">\r\n");
      out.write("                    <a href=\"http://www.ppdai.com/borrow\"  category=\"Borrow\">我要借款</a>\r\n");
      out.write("                    <div class=\"subMenu\">\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/borrow\">我要借款</a>\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/help/howtoborrow\">如何借款</a>\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/borrow/interestcalculate\">利息计算器</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"hasSubMenu\">\r\n");
      out.write("                    <a href=\"http://www.ppdai.com/account\" class='tabon' category=\"Account\">我的账户</a>\r\n");
      out.write("                    <div class=\"subMenu\">\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/account/borrow\">借款账户</a>\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/account/lend\">投资账户</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"hasSubMenu\">\r\n");
      out.write("                    <a href=\"http://www.ppdai.com/help/aboutus\"  category=\"About\">关于我们</a>\r\n");
      out.write("                    <div class=\"subMenu\">\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/help/aboutus\">关于我们</a>\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/help/howworks\">工作原理</a>\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/help/fees\">资费说明</a>\r\n");
      out.write("                      \t<a href=\"http://www.ppdai.com/job\">招贤纳士</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!--头部结束-->\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<div class=\"w100per maintop\"></div>\r\n");
      out.write("<div class=\"my-frame\">\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("    <ul class=\"breadcrumb\" style=\"border: none !important;\">\r\n");
      out.write("        <li><a href=\"http://www.ppdai.com/\">首页</a> <span class=\"divider\">&gt;</span></li>\r\n");
      out.write("            <li><a href=\"http://www.ppdai.com/account/lend\">我的账户-我是投资者</a> <span class=\"divider\">></span></li>\r\n");
      out.write("                    <li><a href=\"/order/online\">即时充值</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("    var breadcrumbCategory = \"Account\";\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<div class=\"clearfix\"></div>\r\n");
      out.write("<div class=\"my-f-left fl\">\r\n");
      out.write("    <div class=\"my-f-l-nav\">我的账户</div>\r\n");
      out.write("    <ul class=\"my-f-l-list\">\r\n");
      out.write("            <li><a href=\"http://www.ppdai.com/account/lend\">我的账户首页</a></li>\r\n");
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("    <div class=\"my-f-l-nav\">资金管理</div>\r\n");
      out.write("    <ul class=\"my-f-l-list\">\r\n");
      out.write("        <li><a href=\"http://www.ppdai.com/moneyhistory\">资金记录</a></li>\r\n");
      out.write("            <li><a href=\"http://pay.ppdai.com/order/online\" class=\"on\">充值</a></li>\r\n");
      out.write("\r\n");
      out.write("            <li><a href=\"http://pay.ppdai.com/trade/cashWithDrawal\">提现</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("        <div class=\"my-f-l-nav\">投资管理</div>\r\n");
      out.write("        <ul class=\"my-f-l-list\">\r\n");
      out.write("            <li><a href=\"http://www.ppdai.com/paybackLendReceived\">投资列表</a></li>\r\n");
      out.write("            <li><a href=\"http://www.ppdai.com/myproduct/ppb/1\">彩虹计划</a></li>\r\n");
      out.write("            <li><a href=\"http://www.ppdai.com/myproduct/yxb/1\">我的拍小宝</a></li>\r\n");
      out.write("            <li><a href=\"http://www.ppdai.com/debtdeal/Negotiable/Apply\">债权交易</a></li>\r\n");
      out.write("            <li><a href=\"http://www.ppdai.com/autobid/addrule\">自动投标</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"my-f-l-nav\">账户设置</div>\r\n");
      out.write("    <ul class=\"my-f-l-list\">\r\n");
      out.write("        <li><a href=\"http://ac.ppdai.com/safe/setting\">账户安全</a></li>\r\n");
      out.write("        <li><a href=\"http://ac.ppdai.com/user/accountbind\">关联账户</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <div class=\"my-f-l-nav\">市场推广</div>\r\n");
      out.write("    <ul class=\"my-f-l-list\">\r\n");
      out.write("        <li><a href=\"http://www.ppdai.com/account/spread\">有奖推广</a></li>\r\n");
      out.write("        <li><a href=\"http://www.ppdai.com/account/paimoney/market?menu\">拍币兑换</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"clearfix\">\r\n");
      out.write("        <div class=\"my-f-right fr\">\r\n");
      out.write("            <div class=\"my-f-r-main mt0\" style=\"border-bottom: solid 1px #e0e0e0;\">\r\n");
      out.write("                <div class=\"my-f-r-ppb clearfix\">\r\n");
      out.write("                    <div class=\"keeping on fl\"><a href=\"/order/online\" style=\"color: #39a1ea;\">即时充值</a></div>\r\n");
      out.write("                    <div class=\"outed fl\"><a href=\"/order/offline\">非即时充值（免费）</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"my-ac-balance\">可用余额：<span class=\"my-ac-balanceNum\">&#165;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${balanceMoney}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write(" </span></div>\r\n");
      out.write("                <div class=\"my-ac-recharge\" style=\"padding-top: 3px;\">\r\n");
      out.write("                    <p style=\"line-height: 78px;\">充值方式：<span class=\"c666666\">支持多家银行借记卡充值；支持支付宝、财付通多种充值平台.</span></p>\r\n");
      out.write("                    <form action=\"recordController/addrecordOne\" method=\"POST\" id=\"aibankform\">\r\n");
      out.write("                        <div class=\"card_nav\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <table cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                                <input name=\"SelectedBankId\" type=\"radio\" value=\"2\" channel=\"2\" class=\"balpay\" />\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                                <span class=\"zhifu inititem\" style=\"cursor: pointer;\"></span>\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                                <input name=\"SelectedBankId\" type=\"radio\" value=\"3\" channel=\"3\" class=\"balpay\" />\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                                <span class=\"t_caifu inititem\" style=\"cursor: pointer;\"></span>\r\n");
      out.write("                                            </td>\r\n");
      out.write("\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td colspan=\"4\">\r\n");
      out.write("                                            <div class=\"my-ac-rc-other morebank\">选择其他方式充值</div>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"bank_nav\" style=\"display: none;\">\r\n");
      out.write("                                <div class=\"bank p1\">\r\n");
      out.write("                                    <div class=\"title\">支付平台</div>\r\n");
      out.write("                                    <div class=\"content\">\r\n");
      out.write("                                        <table cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                    <td>\r\n");
      out.write("                                                        <input name=\"SelectedBankId\" type=\"radio\" value=\"2\" channel=\"2\" style=\"margin-left: 0;\" class=\"balpay\"/>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td>\r\n");
      out.write("                                                        <span class=\"zhifu item\" style=\"cursor: pointer;\"></span>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td>\r\n");
      out.write("                                                        <input name=\"SelectedBankId\" channel=\"3\" type=\"radio\" value=\"3\" class=\"balpay\"/>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td>\r\n");
      out.write("                                                        <span class=\"t_caifu item\" style=\"cursor: pointer;\"></span>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </table>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"bank p2\">\r\n");
      out.write("                                    <div class=\"title\">网上银行</div>\r\n");
      out.write("                                    <div class=\"content\">\r\n");
      out.write("                                        <ul class=\"instant_ok_banklist_nav\">\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"5\" channel=\"6\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image: ./jsp/ppd_recharge_files/bank_gs.gif;\" title=\"中国工商银行\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_gs.gif\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"9\" channel=\"6\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image:./jsp/ppd_recharge_files/bank_ny.gif;\" title=\"中国农业银行\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_ny.gif\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"7\" channel=\"6\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image: ./jsp/ppd_recharge_files/bank_js.gif;\" title=\"中国建设银行\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_js.gif\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"8\" channel=\"6\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image: ./jsp/ppd_recharge_files/bank_zg.gif;\" title=\"中国银行\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_zg.gif\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"6\" channel=\"6\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image:./jsp/ppd_recharge_files/bank_zs.gif;\" title=\"招商银行\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_zs.gif\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"10\" channel=\"6\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image: ./jsp/ppd_recharge_files/bank_jt.gif;\" title=\"交通银行\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_jt.gif\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"11\" channel=\"6\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image:./jsp/ppd_recharge_files/bank_yzcx.gif;\" title=\"中国邮政储蓄银行\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_yzcx.gif\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"12\" channel=\"6\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image: ./jsp/ppd_recharge_files/bank_gd.gif;\" title=\"中国光大银行\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_gd.gif\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"13\" channel=\"6\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image: ./jsp/ppd_recharge_files/bank_pf.gif;\" title=\"浦发银行\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_pf.gif\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"14\" channel=\"2\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image: ./jsp/ppd_recharge_files/bank_gf.gif;\" title=\"广发银行\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_gf.gif\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"15\" channel=\"6\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image: ./jsp/ppd_recharge_files/bank_ms.gif;\" title=\"中国民生银行\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_ms.gif\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"16\" channel=\"6\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image:./jsp/ppd_recharge_files/bank_bj.gif;\" title=\"北京银行\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_bj.gif\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"17\" channel=\"6\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image: ./jsp/ppd_recharge_files/bank_bjncsy.gif;\" title=\"北京农村商业银行\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_bjncsy.gif\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"18\" channel=\"2\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image: ./jsp/ppd_recharge_files/bank_fd.gif;\" title=\"富滇银行\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_fd.gif\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"19\" channel=\"6\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image: ./jsp/ppd_recharge_files/bank_zx.gif;\" title=\"中信银行\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_zx.gif\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"20\" channel=\"6\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image: ./jsp/ppd_recharge_files/bank_xy.gif;\" title=\"兴业银行\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_xy.gif\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"21\" channel=\"4\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image: ./jsp/ppd_recharge_files/bank_sh.gif;\" title=\"上海银行\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_sh.gif\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"22\" channel=\"6\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image: ./jsp/ppd_recharge_files/bank_pa.gif;\" title=\"平安银行\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_pa.gif\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"23\" channel=\"6\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image: ./jsp/ppd_recharge_files/bank_nb.gif;\" title=\"宁波银行\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_nb.gif\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"25\" channel=\"2\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image: ./jsp/ppd_recharge_files/bank_ccbbtb.png;\" title=\"中国建设银行-企业\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_ccbbtb.png\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"26\" channel=\"2\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image: ./jsp/ppd_recharge_files/bank_abcbtb.png;\" title=\"中国农业银行-企业\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_abcbtb.png\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <input name=\"SelectedBankId\" type=\"radio\"  value=\"27\" channel=\"2\" />\r\n");
      out.write("                                                    <label>\r\n");
      out.write("                                                        <span class=\"icon icbc105 item\" style=\"cursor: pointer;list-style-image: ./jsp/ppd_recharge_files/bank_pfbtb.png;\" title=\"浦发银行-企业\">\r\n");
      out.write("                                                            <img src=\"./jsp/ppd_recharge_files/bank_pfbtb.png\" /></span>\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </li>\r\n");
      out.write("\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mt15 clearfix \">\r\n");
      out.write("                            <label class=\"lh32 my-ac-rc-fel fl\">充值金额：</label><input class=\"my-ac-rc-jine fl\" name=\"deposit\" id=\"Amount\" type=\"text\" autocomplete=\"off\"\r\n");
      out.write("                                value=\"0\" data-validation-engine=\"validate[required]\" maxlength=\"8\" /><span class=\"my-ac-rc-yuan fl\">元</span>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                            <div class=\"mt12 lh32\" style=\"display: none;\">\r\n");
      out.write("                                <label style=\"display: none;\"><span class=\"my-ac-rc-fel\">实际到账：</span><span id=\"factAmount\" style=\"height: 30px; line-height: 30px;\">￥0.00</span></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mt12 lh32\" style=\"display: none;\">\r\n");
      out.write("                                <label><span class=\"my-ac-rc-fel\">预估手续费：</span><span><span id=\"fee\">￥0.00</span></span></label><a class=\"c39a1ea\" href=\"javascript:void()\" title=\"第三方支付收取充值费1%（财付通9折），拍拍贷提供给您的免费充值流量：&#165;0.00元。实际完成充值时，手续费优先使用免费流量，如果不足，则超出部分按正常收取。\">【收费规则】</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <input type=\"submit\" class=\"my-blue-btn mt30\" style=\"display:inline-block;width: 250px; height: 50px; line-height: 50px; text-align: center;margin-left:100px; cursor:pointer;\" value=\"免费充值\" id=\"btnOk\">\r\n");
      out.write("                            <span class=\"error\" style=\"color: red; padding-top: 21px; padding-left: 10px;\">\r\n");
      out.write("<label for=\"\">*投资者前三次即时到账充值免费*</label>                                                            </span>\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <input type=\"hidden\" id=\"hidUserId\" value=\"5105760\"  />\r\n");
      out.write("                        <input id=\"Redirect\" name=\"Redirect\" type=\"hidden\" value=\"\" />\r\n");
      out.write("                    </form>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"instant_recharge_three\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    温馨说明：\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>1、充值资金可用于进行多项认证、投标、还款等。</li>\r\n");
      out.write("                    <li>2、所有资金将由第三方平台 支付宝、财付通、银行等托管，拍拍贷本身不存放用户的投标保证金。</li>\r\n");
      out.write("                    <li>3、省手续费，推荐使用“<a href=\"/order/offline\" target=\"_blank\" class=\"c39a1ea\">非即时到账充值</a>”，最高10元/笔，<a href=\"http://www.ppdai.com/info/vip\" target=\"_blank\">VIP</a>单笔充值1千（含）元以上，免手续费。</li>\r\n");
      out.write("                    <li>4、手续费减免：有免费流量时会根据免费流量减免手续费；交易时以实际完成交易的时间为准，先完成的交易会优先使用掉免费流量。</li>\r\n");
      out.write("                    <li>5、借出者推荐使用“<a href=\"/order/offline\" target=\"_blank\" class=\"c39a1ea\">非即时到账充值</a>”，充值免费。</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    var inpourAmountMax = 10000000\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("    var freeAmout = 0.0000\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"./jsp/ppd_recharge_files/order.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"clear\">\r\n");
      out.write("    </div>\r\n");
      out.write("     <!--底部-->\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("        <div class=\"footer_footerBottom\">\r\n");
      out.write("            <ul class=\"footer_footerBottomNav clearfix\">\r\n");
      out.write("                <li><span class=\"webindex\"></span><a href=\"http://www.ppdai.com/\">网站首页</a>|</li>\r\n");
      out.write("                <li><span class=\"aboutus\"></span><a href=\"http://www.ppdai.com/help/aboutus\">关于我们</a>|</li>\r\n");
      out.write("                <li><span class=\"mapsite\"></span><a href=\"http://www.ppdai.com/home/sitemap\">网站地图</a>|</li>\r\n");
      out.write("                <li><span class=\"webservice\"></span><a href=\"http://www.ppdai.com/consult\">客服中心</a>|</li>\r\n");
      out.write("                <li class=\"nomr\"><span class=\"onlneserve\"></span><a href=\"http://wpa.b.qq.com/cgi/wpa.php?ln=1&key=XzgwMDAyNzUzNV8xODAzNjBfODAwMDI3NTM1XzJf\" target=\"_blank\">在线咨询</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <p>Copyright Reserved 2007-2015©拍拍贷（www.ppdai.com）&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;沪ICP备05063398号&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;上海拍拍贷金融信息服务有限公司</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--底部结束-->\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("        $(\".my-f-l-list li a.on\").closest(\".my-f-l-list\").prev(\".my-f-l-nav\").addClass(\"my-f-l-nav-sd\");\r\n");
      out.write("        $(\"#tabIcon a[category='\" + breadcrumbCategory + \"']\").addClass(\"tabon\");\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"http://ac.ppdai.com/status?v=2014\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        var _gaq = _gaq || [];\r\n");
      out.write("        _gaq.push(['_setAccount', 'UA-3635664-1']);\r\n");
      out.write("        _gaq.push(['_setDomainName', 'ppdai.com']);\r\n");
      out.write("        _gaq.push(['_setAllowHash', false]);\r\n");
      out.write("        _gaq.push([\"_addOrganic\", \"baidu\", \"word\"]);\r\n");
      out.write("        _gaq.push([\"_addOrganic\", \"soso\", \"w\"]);\r\n");
      out.write("        _gaq.push([\"_addOrganic\", \"soso\", \"key\"]);\r\n");
      out.write("        _gaq.push([\"_addOrganic\", \"sogou\", \"query\"]);\r\n");
      out.write("        _gaq.push([\"_addOrganic\", \"sogou\", \"keyword\"]);\r\n");
      out.write("        _gaq.push(['_addOrganic', 'youdao', 'q']);\r\n");
      out.write("        _gaq.push([\"_addOrganic\", \"so.com\", \"q\"]);\r\n");
      out.write("        _gaq.push([\"_addOrganic\", \"m.baidu.com\", \"word\"]);\r\n");
      out.write("        _gaq.push(['_trackPageview']);\r\n");
      out.write("        (function () {\r\n");
      out.write("            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;\r\n");
      out.write("            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';\r\n");
      out.write("            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);\r\n");
      out.write("        })();\r\n");
      out.write("    </script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        var _bdhmProtocol = ((\"https:\" == document.location.protocol) ? \" https://\" : \" http://\");\r\n");
      out.write("        document.write(unescape(\"%3Cscript src='\" + _bdhmProtocol + \"hm.baidu.com/h.js%3Faab1030ecb68cd7b5c613bd7a5127a40' type='text/javascript'%3E%3C/script%3E\"));\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
