package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class myaccount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\r\n");
      out.write("<!-- saved from url=(0036)http://loan.ppdai.com/account/borrow -->\r\n");
      out.write("<HTML><HEAD>\r\n");
      out.write("<TITLE>我的账户-中国首家，最大、最多人使用的互联网金融P2P网络借贷平台。提供小额贷款,短期贷款,个人贷款,自定利率,借期灵活。您还可以成为借出人理财投资,超低门槛，获得高年收益率回报</TITLE>\r\n");
      out.write("<META content=\"text/html; charset=utf-8\" http-equiv=Content-Type>\r\n");
      out.write("<META name=viewport content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<META name=description \r\n");
      out.write("content=拍拍贷，中国首家，最大、最多人使用的互联网金融P2P(人人贷)网络借贷平台。提供小额贷款,短期贷款,个人贷款,抵押,无抵押贷款服务。利率自定,借期灵活。您还可以成为借出人理财借贷投资，获得高年收益率回报，超低门槛，超高收益。作为可信赖的投融资,理财,贷款,信贷平台,拍拍贷助您财富实现增值>\r\n");
      out.write("<META name=keywords \r\n");
      out.write("content=网络贷款,民间借贷,小额贷款,无抵押贷款,信用贷款,网络借贷,借贷平台,拍拍贷,人人贷,投资理财,个人理财,p2p贷款,贷款,互联网金融,投融资><LINK \r\n");
      out.write("rel=stylesheet type=text/css href=\"我的账户_files/basic.css\"><LINK rel=stylesheet \r\n");
      out.write("type=text/css href=\"CSS/layout.css\"><LINK rel=stylesheet \r\n");
      out.write("href=\"CSS/validation-min.css\"><LINK rel=\"shortcut icon\" type=image/x-icon \r\n");
      out.write("href=\"http://www.ppdaicdn.com/favicon.ico\">\r\n");
      out.write("<SCRIPT src=\"CSS/newRefer.js\"></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT type=text/javascript>\r\n");
      out.write("        var _bdhmProtocol = ((\"https:\" == document.location.protocol) ? \" https://\" : \" http://\");\r\n");
      out.write("        document.write(unescape(\"%3Cscript src='\" + _bdhmProtocol + \"hm.baidu.com/h.js%3Faab1030ecb68cd7b5c613bd7a5127a40' type='text/javascript'%3E%3C/script%3E\"));\r\n");
      out.write("    </SCRIPT>\r\n");
      out.write("<LINK rel=stylesheet href=\"CSS/account.css\"><LINK rel=stylesheet \r\n");
      out.write("href=\"CSS/jr.css\">\r\n");
      out.write("\r\n");
      out.write("<META name=GENERATOR content=\"MSHTML 8.00.7600.17267\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/account.css\" type=\"text/css\"></link>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/basic.css\" type=\"text/css\"></link>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/jr.css\" type=\"text/css\"></link>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/layout.css\" type=\"text/css\"></link>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/validation-min.css\" type=\"text/css\"></link>\r\n");
      out.write("</HEAD>\r\n");
      out.write("<BODY>\r\n");
      out.write("<DIV class=\"top PPD_header_nav\">\r\n");
      out.write("<DIV class=\"top_inner w1188center clearfix PPD_login_status\"></DIV></DIV>\r\n");
      out.write("<DIV class=mainNav>\r\n");
      out.write("<DIV class=\"mainNav_inner w1000center clearfix\">\r\n");
      out.write("<H1 class=logo><A href=\"http://loan.ppdai.com/\"><IMG alt=\"\" \r\n");
      out.write("src=\"CSS/logo.png\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<img src=\"CSS/logo.png\"/></A> </H1>\r\n");
      out.write("<UL id=tabIcon>\r\n");
      out.write("  <LI class=hasSubMenu><A href=\"http://www.ppdai.com/lend\" \r\n");
      out.write("  category=\"Lend\">我要投资</A> \r\n");
      out.write("  <DIV class=subMenu><A href=\"http://www.ppdai.com/lend\">我要投资</A> <A \r\n");
      out.write("  href=\"http://www.ppdai.com/product/plan/rainbow\">彩虹计划</A> <A \r\n");
      out.write("  href=\"http://www.ppdai.com/debtdeal/AlldebtList/DebtList\">债权交易</A> <A \r\n");
      out.write("  href=\"http://www.ppdai.com/howtolend\">如何投资</A> <A \r\n");
      out.write("  href=\"http://www.ppdai.com/help/principalprotection\">本金保障</A> </DIV></LI>\r\n");
      out.write("  <LI class=hasSubMenu><A href=\"http://loan.ppdai.com/borrow\" \r\n");
      out.write("  category=\"Borrow\">我要借款</A> \r\n");
      out.write("  <DIV class=subMenu><A href=\"http://loan.ppdai.com/borrow\">我要借款</A> <A \r\n");
      out.write("  href=\"http://www.ppdai.com/help/howtoborrow\">如何借款</A> <A \r\n");
      out.write("  href=\"http://www.ppdai.com/borrow/interestcalculate\">利息计算器</A> </DIV></LI>\r\n");
      out.write("  <LI class=hasSubMenu><A href=\"http://loan.ppdai.com/account\" \r\n");
      out.write("  category=\"Account\">我的账户</A> \r\n");
      out.write("  <DIV class=subMenu><A href=\"http://loan.ppdai.com/account/borrow\">借款账户</A> <A \r\n");
      out.write("  href=\"http://www.ppdai.com/account/lend\">投资账户</A> </DIV></LI>\r\n");
      out.write("  <LI class=hasSubMenu><A href=\"http://www.ppdai.com/help/aboutus\" \r\n");
      out.write("  category=\"About\">关于拍拍贷</A> \r\n");
      out.write("  <DIV class=subMenu><A href=\"http://www.ppdai.com/help/aboutus\">关于我们</A> <A \r\n");
      out.write("  href=\"http://www.ppdai.com/help/howworks\">工作原理</A> <A \r\n");
      out.write("  href=\"http://www.ppdai.com/help/fees\">资费说明</A> <A \r\n");
      out.write("  href=\"http://www.ppdai.com/job\">招贤纳士</A> </DIV></LI></UL></DIV></DIV>\r\n");
      out.write("<DIV class=\"w100per maintop\"></DIV>\r\n");
      out.write("<DIV class=my-frame><!-- 子导航-->\r\n");
      out.write("<DIV>\r\n");
      out.write("<UL \r\n");
      out.write("style=\"BORDER-BOTTOM-STYLE: none !important; BORDER-RIGHT-STYLE: none !important; BORDER-TOP-STYLE: none !important; BORDER-LEFT-STYLE: none !important\" \r\n");
      out.write("class=breadcrumb>\r\n");
      out.write("  <LI><A href=\"http://loan.ppdai.com/\">首页</A> <SPAN class=divider>&gt;</SPAN> \r\n");
      out.write("  <LI><A href=\"http://loan.ppdai.com/account/borrow\">我的账户-我是借款者</A> <SPAN \r\n");
      out.write("  class=divider>&gt;</SPAN> \r\n");
      out.write("  <LI><A href=\"http://loan.ppdai.com/account/borrow\">我的账户</A> </LI></UL></DIV>\r\n");
      out.write("<SCRIPT>\r\n");
      out.write("    var breadcrumbCategory = \"Account\";\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<DIV class=clearfix><!-- 左菜单栏-->\r\n");
      out.write("<DIV class=\"my-f-left fl\">\r\n");
      out.write("<DIV class=my-f-l-nav>我的账户</DIV>\r\n");
      out.write("<UL class=my-f-l-list>\r\n");
      out.write("  <LI><A class=on href=\"http://loan.ppdai.com/account/borrow\">我的账户首页</A> \r\n");
      out.write("</LI></UL>\r\n");
      out.write("<DIV class=my-f-l-nav>资金管理</DIV>\r\n");
      out.write("<UL class=my-f-l-list>\r\n");
      out.write("  <LI><A href=\"http://www.ppdai.com/moneyhistory\">资金记录</A> </LI>\r\n");
      out.write("  <LI><A href=\"http://pay.ppdai.com/order/online\">充值</A> </LI>\r\n");
      out.write("  <LI><A href=\"http://pay.ppdai.com/trade/cashwithdrawal\">提现</A> </LI></UL>\r\n");
      out.write("<DIV class=my-f-l-nav>借款管理</DIV>\r\n");
      out.write("<UL class=my-f-l-list>\r\n");
      out.write("  <LI><A href=\"http://loan.ppdai.com/account/repaymentlist\">我的借款</A> </LI>\r\n");
      out.write("  <LI><A href=\"http://www.ppdai.com/user/auth/videouser\">信息认证</A> </LI>\r\n");
      out.write("  <LI><A href=\"http://www.ppdai.com/info/userdetail\">基本资料</A> </LI>\r\n");
      out.write("  <LI><A href=\"http://www.ppdai.com/info/userdocuments\">上传资料</A> </LI></UL>\r\n");
      out.write("<DIV class=my-f-l-nav>账户设置</DIV>\r\n");
      out.write("<UL class=my-f-l-list>\r\n");
      out.write("  <LI><A href=\"http://ac.ppdai.com/safe/setting\">安全中心</A> </LI>\r\n");
      out.write("  <LI><A href=\"http://ac.ppdai.com/user/accountbind\">关联账户</A> </LI></UL>\r\n");
      out.write("<DIV class=my-f-l-nav>市场推广</DIV>\r\n");
      out.write("<UL class=my-f-l-list>\r\n");
      out.write("  <LI><A href=\"http://www.ppdai.com/account/spread\">有奖推荐</A> </LI>\r\n");
      out.write("  <LI><A href=\"http://www.ppdai.com/account/paimoney/market?menu\">拍币兑换</A> </LI>\r\n");
      out.write("  <LI><A href=\"http://www.ppdai.com/account/raffletickets\">我的抽奖券</A> \r\n");
      out.write("</LI></UL></DIV>\r\n");
      out.write("<DIV class=\"my-f-right c666666 fr\">\r\n");
      out.write("<DIV class=my-ac-haowai>\r\n");
      out.write("<DIV class=extra><SPAN class=float_l>号外：</SPAN><LABEL>新版“拍”了传（安卓版）资料上传更方便啦，<A \r\n");
      out.write("class=c39a1ea \r\n");
      out.write("href=\"http://www.ppdai.com/info/userdocuments?haowai\">点击下载</A>吧</LABEL>！ \r\n");
      out.write("</DIV></DIV>\r\n");
      out.write("<DIV class=\"jr_h01 clearfix\">\r\n");
      out.write("<DIV class=\"my-ac-users jr13 fl \">\r\n");
      out.write("<DIV class=my-ac-userHead><A href=\"http://loan.ppdai.com/info/userface/\"><IMG \r\n");
      out.write("alt=用户头像 src=\"CSS/nophoto_80.jpg\" width=150 height=150> </A>\r\n");
      out.write("<DIV class=my-ac-vfr><A class=\"my-ac-vfs my-ac-vidh fl\" title=身份认证 \r\n");
      out.write("href=\"http://loan.ppdai.com/cert/identitycert\"></A><A \r\n");
      out.write("class=\"my-ac-vfs my-ac-vphoneh ml17 fl\" title=手机绑定 \r\n");
      out.write("href=\"http://ac.ppdai.com/userbind/bindmobile\"></A><A \r\n");
      out.write("class=\"my-ac-vfs my-ac-vvideo \" title=视频认证 \r\n");
      out.write("href=\"http://loan.ppdai.com/cert/videousercert\"></A></DIV></DIV>\r\n");
      out.write("<DIV class=\"w600 my-ac-userInfo\">\r\n");
      out.write("<DIV class=\"my-ac-userverfy clearfix\"><LABEL \r\n");
      out.write("class=\"my-ac-username fl\">pdu11557782</LABEL> <A \r\n");
      out.write("class=\"my-ac-dgvip my-ac-dgvip3 fl\" title=您还不是VIP \r\n");
      out.write("href=\"http://loan.ppdai.com/info/vip\"></A></DIV>\r\n");
      out.write("<DIV class=clearfix>\r\n");
      out.write("<DIV class=\"my-ac-paisafty fl\">\r\n");
      out.write("<DIV class=my-ac-ps-one><LABEL class=taJustify>拍币：</LABEL><SPAN id=paiMoney \r\n");
      out.write("class=\"c39a1ea mr20\">197</SPAN> <LABEL class=\"my-ac-qiandao my-ac-qdq\"><SPAN \r\n");
      out.write("id=btnGetPaiMoney class=\"signIn hover\">签到</SPAN> <SPAN class=\"exchange hover\"><A \r\n");
      out.write("href=\"http://loan.ppdai.com/account/paimoney/market\">兑换</A></SPAN> \r\n");
      out.write("</LABEL></DIV>\r\n");
      out.write("<DIV class=\"my-ac-ps-two clearfix\"><LABEL class=taJustify>账户安全：</LABEL><SPAN \r\n");
      out.write("class=\"my-ac-ps-twomark my-ac-ps-twok2\"></SPAN><SPAN><A \r\n");
      out.write("href=\"http://ac.ppdai.com/safe/setting\">【增强】</A></SPAN> </DIV>\r\n");
      out.write("<DIV class=lastLoginTime></DIV></DIV></DIV></DIV></DIV>\r\n");
      out.write("<DIV class=\"jr_13 fl\">\r\n");
      out.write("<DIV class=\"jr_13bg fl\">\r\n");
      out.write("<DIV class=\"jr_13ei \">\r\n");
      out.write("<DIV class=jr_13tit>信用额度</DIV>\r\n");
      out.write("<DIV class=\"jr_ein fl\">\r\n");
      out.write("<P style=\"Z-INDEX: 1; POSITION: relative\" class=jr_t01>可用额度&nbsp;: <IMG \r\n");
      out.write("style=\"POSITION: absolute; TOP: 5px; LEFT: 76px\" title=目前可申请借款的额度 \r\n");
      out.write("src=\"CSS/wenhao.png\"> </P>\r\n");
      out.write("<P class=\"jr_t02 cf7971a\">3,000</P>\r\n");
      out.write("<P style=\"Z-INDEX: 1; POSITION: relative\" class=jr_t03>总额度&nbsp;: <IMG \r\n");
      out.write("style=\"POSITION: absolute; TOP: 5px; LEFT: 62px\" title=最多可借额度，可用额度和已借额度之和 \r\n");
      out.write("src=\"CSS/wenhao.png\"> </P>\r\n");
      out.write("<P class=jr_t02>3,000</P></DIV>\r\n");
      out.write("<DIV class=\"jr_ein1 fl\"><!--\r\n");
      out.write("                                        原图\r\n");
      out.write("                                        <img src=\"http://www.ppdaicdn.com/2014/img/11_03.jpg\">\r\n");
      out.write("                                        -->\r\n");
      out.write("<DIV class=jr_jd_outer>\r\n");
      out.write("<DIV id=scaleMap class=jr_jd></DIV>\r\n");
      out.write("<DIV class=jr_jdl><A \r\n");
      out.write("href=\"http://www.ppdai.com/borrow\">立即借款&gt;</A></DIV></DIV></DIV></DIV></DIV>\r\n");
      out.write("<DIV class=\"jr_13hr fl\"></DIV>\r\n");
      out.write("<DIV class=\"pl35 pt18 fl\">\r\n");
      out.write("<DIV style=\"COLOR: #333; FONT-SIZE: 18px\" class=jr_13tit01>账户余额<IMG \r\n");
      out.write("style=\"MARGIN-LEFT: 3px\" title=可用于还款或提现 src=\"CSS/wenhao.png\"></DIV>\r\n");
      out.write("<DIV class=lh50><SPAN class=my-ac-ps-yue>¥0</SPAN></DIV>\r\n");
      out.write("<DIV class=taCenter><A class=\"my-blue-btn my-ac-btns\" \r\n");
      out.write("href=\"http://pay.ppdai.com/order/online\" target=_blank>充值</A><A \r\n");
      out.write("class=\"ml16 my-yellow-btn my-ac-btns\" \r\n");
      out.write("href=\"http://pay.ppdai.com/trade/cashwithdrawal\" \r\n");
      out.write("target=_blank>提现</A></DIV></DIV></DIV></DIV>\r\n");
      out.write("<DIV class=my-bor-frame>\r\n");
      out.write("<DIV class=\"my-bor-gobidfr bgf8\">\r\n");
      out.write("<DIV class=\"my-ac-ctTitle clearfix\"><SPAN \r\n");
      out.write("class=\"fs18 fl\">当前借款</SPAN></DIV></DIV>\r\n");
      out.write("<DIV>\r\n");
      out.write("<P class=\" mt10 pl40 lh30\">借款列表：<A class=c39a1ea \r\n");
      out.write("href=\"http://loan.ppdai.com/list/1895978\">【个人消费】新房装修，请速满标。谢谢。</A></P>\r\n");
      out.write("<P class=\"lh30 pl40 clearfix\"><SPAN class=fl>金额：¥3,000.00</SPAN><SPAN \r\n");
      out.write("class=\"fl ml40\">期限：6个月</SPAN></P></DIV>\r\n");
      out.write("<DIV class=\"my-bor-lc clearfix\"><A href=\"http://loan.ppdai.com/firstuserdetail\">\r\n");
      out.write("<DIV class=\"lc grxx1 fl\"></DIV></A>\r\n");
      out.write("<DIV class=\"hxone lcgreen fl\"></DIV><A \r\n");
      out.write("href=\"http://loan.ppdai.com/firstcreatelist\">\r\n");
      out.write("<DIV class=\"lc jkxx1 fl\"></DIV></A>\r\n");
      out.write("<DIV class=\"hxtwo lcgreen fl\"></DIV><A \r\n");
      out.write("href=\"http://loan.ppdai.com/firstdocuments\">\r\n");
      out.write("<DIV class=\"lc zzsh2 fl\">\r\n");
      out.write("<DIV class=lc-jt></DIV></DIV></A>\r\n");
      out.write("<DIV class=\"hxthree lcgay fl\"></DIV>\r\n");
      out.write("<DIV class=\"lc cjzj3 fl\"></DIV></DIV>\r\n");
      out.write("<DIV class=lc-ts-four-ts><A href=\"http://loan.ppdai.com/firstuserdetail\"><SPAN \r\n");
      out.write("class=c8fc320>个人信息</SPAN></A> <A \r\n");
      out.write("href=\"http://loan.ppdai.com/firstcreatelist\"><SPAN \r\n");
      out.write("class=\"c8fc320 ml96\">借款信息</SPAN></A> <A \r\n");
      out.write("href=\"http://loan.ppdai.com/firstdocuments\"><SPAN \r\n");
      out.write("class=\"cf7971a ml86\">资质审核</SPAN></A> <SPAN class=\"c666666 ml86\">筹集资金</SPAN> \r\n");
      out.write("</DIV>\r\n");
      out.write("<DIV class=lc-ts-frame>\r\n");
      out.write("<DIV class=\"ts c666666\">\r\n");
      out.write("<P class=lh30><SPAN class=cff6600>综合评分未达标，审核失败。 ×</SPAN><A \r\n");
      out.write("style=\"MARGIN-LEFT: 20px\" class=c39a1ea \r\n");
      out.write("href=\"http://loan.ppdai.com/firstcreatelist\">重新借款</A> </P></DIV></DIV></DIV>\r\n");
      out.write("<DIV \r\n");
      out.write("style=\"PADDING-BOTTOM: 19px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 19px\" \r\n");
      out.write("class=\"my-bor-ops clearfix\"><A class=\"op1 fl\" \r\n");
      out.write("href=\"http://loan.ppdai.com/info/userdetail\">填写基本资料</A> <A class=\"ml11 op2 fl\" \r\n");
      out.write("href=\"http://loan.ppdai.com/info/userdocuments\">上传资料</A> <A class=\"ml11 op3 fl\" \r\n");
      out.write("href=\"http://loan.ppdai.com/user/auth/mobile\">手机实名认证</A> <A class=\"ml11 op4 fl\" \r\n");
      out.write("href=\"http://ac.ppdai.com/user/accountbind\">关联账户</A> </DIV></DIV></DIV><INPUT \r\n");
      out.write("id=IsFinishSwitchBorrowLoan value=0 type=hidden> </DIV><!-- 意见框 -->\r\n");
      out.write("<DIV style=\"DISPLAY: none\" id=cover class=cover></DIV>\r\n");
      out.write("<DIV style=\"DISPLAY: none\" id=suggestion_box class=suggestion_box>\r\n");
      out.write("<DIV class=suggestion_title>版本切换</DIV>\r\n");
      out.write("<DIV class=suggestion_body>\r\n");
      out.write("<P>真的不爱新版吗？有什么不满意的,我改还不好么？T^T</P><TEXTAREA id=Description placeholder=\"留下不满意的原因,让我改好吗..\"></TEXTAREA> \r\n");
      out.write("</DIV>\r\n");
      out.write("<DIV class=suggestion_btnBox><INPUT id=submitbtn value=提个意见,继续用新版 type=button> <INPUT id=v2013 class=closeSuggestion value=没法忍,我要用旧版 type=button> </DIV><A \r\n");
      out.write("class=\"suggestion_close closeSuggestion\" href=\"javascript:;\">×</A> </DIV><!-- 意见框 结束 --><!-- 体验版意见框 -->\r\n");
      out.write("<DIV style=\"DISPLAY: none\" id=suggestion_box1 class=suggestion_box>\r\n");
      out.write("<DIV class=suggestion_title>版本切换</DIV>\r\n");
      out.write("<DIV class=suggestion_body>\r\n");
      out.write("<P>真的不爱体验版吗？有什么不满意的,我改还不好么？T^T</P><TEXTAREA id=Description1 placeholder=\"留下不满意的原因,让我改好吗..\"></TEXTAREA> \r\n");
      out.write("</DIV>\r\n");
      out.write("<DIV class=suggestion_btnBox><INPUT id=submitbtn1 value=提个意见,继续用新版 type=button> <INPUT id=vison class=closeSuggestion value=没法忍,我要用旧版 type=button> </DIV><A \r\n");
      out.write("class=\"suggestion_close closeSuggestion\" href=\"javascript:;\">×</A> </DIV><!-- 体验版意见框 结束 -->\r\n");
      out.write("<DIV class=clear></DIV>\r\n");
      out.write("<DIV class=footer>\r\n");
      out.write("<DIV class=footer_footerBottom>\r\n");
      out.write("<UL class=\"footer_footerBottomNav clearfix\">\r\n");
      out.write("  <LI><SPAN class=webindex></SPAN><A href=\"http://loan.ppdai.com/\">网站首页</A>| \r\n");
      out.write("  </LI>\r\n");
      out.write("  <LI><SPAN class=aboutus></SPAN><A \r\n");
      out.write("  href=\"http://loan.ppdai.com/help/aboutus\">关于我们</A>| </LI>\r\n");
      out.write("  <LI><SPAN class=mapsite></SPAN><A \r\n");
      out.write("  href=\"http://loan.ppdai.com/home/sitemap\">网站地图</A>| </LI>\r\n");
      out.write("  <LI><SPAN class=webservice></SPAN><A \r\n");
      out.write("  href=\"http://loan.ppdai.com/consult\">客服中心</A>| </LI>\r\n");
      out.write("  <LI class=nomr><SPAN class=onlneserve></SPAN><A \r\n");
      out.write("  href=\"http://wpa.b.qq.com/cgi/wpa.php?ln=1&amp;key=XzgwMDAyNzUzNV8xODAzNjBfODAwMDI3NTM1XzJf\" \r\n");
      out.write("  target=_blank>在线咨询</A> </LI></UL>\r\n");
      out.write("<P>Copyright Reserved \r\n");
      out.write("2007-2015©拍拍贷（www.ppdai.com）&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;沪ICP备05063398号&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;上海拍拍贷金融信息服务有限公司</P></DIV></DIV>\r\n");
      out.write("<SCRIPT type=text/javascript charset=utf-8 src=\"CSS/jquery.js\"></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT type=text/javascript charset=utf-8 src=\"CSS/init.js\"></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT src=\"CSS/servicestack-min.js\"></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT src=\"CSS/jquery.cookie.js\"></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT type=text/javascript src=\"CSS/status\"></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT>\r\n");
      out.write("        $(\".my-f-l-list li a.on\").closest(\".my-f-l-list\").prev(\".my-f-l-nav\").addClass(\"my-f-l-nav-sd\");\r\n");
      out.write("        try {\r\n");
      out.write("            $(\"#tabIcon a[category='\" + breadcrumbCategory + \"']\").addClass(\"tabon\");\r\n");
      out.write("        } catch (e) {\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("    </SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT src=\"CSS/bootstrap.min.js\"></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT type=text/javascript src=\"CSS/customize.js\"></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT type=text/javascript charset=utf-8 \r\n");
      out.write("src=\"CSS/echarts-plain.js\"></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT src=\"CSS/scaleMap.js\"></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT src=\"CSS/raphael-min.2.1.2.js\"></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT>\r\n");
      out.write("        $(function () {\r\n");
      out.write("            //新版反馈\r\n");
      out.write("            $(\"#suggestion_box #submitbtn,#suggestion_box .closeSuggestion\").click(function () {\r\n");
      out.write("                    \r\n");
      out.write("                var description = $(\"#suggestion_box #Description\").val() + \"〖 手机号码：\" + 13213132610 + \",QQ号码:\" + 854529175 + \" 〗\";\r\n");
      out.write("        \r\n");
      out.write("                if ($(\"#suggestion_box #Description\").val() != \"\" && $(\"#suggestion_box #Description\").val() != undefined) {\r\n");
      out.write("                    $.post(\"/debtdeal/Negotiable/FeedBack\", { description: description, categoryId: \"120\" }, function (e) {\r\n");
      out.write("                        $(\".fankui_emsg\").html(e.Message);\r\n");
      out.write("                        $(\"#suggestion_box #Description\").val(\"\"); //清空内容\r\n");
      out.write("                    });\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            $(\"#suggestion_box .closeSuggestion,#submitbtn\").click(function () {\r\n");
      out.write("                $(\"#suggestion_box,.cover\").hide();\r\n");
      out.write("            });\r\n");
      out.write("            $('#v2013').click(function () {\r\n");
      out.write("                $.cookie('ui-version', '2013', { expires: 365, path: '/', domain: '.ppdai.com', secure: false });\r\n");
      out.write("                window.location.reload();\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    </SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT>\r\n");
      out.write("        $(function () {\r\n");
      out.write("            //体验版反馈\r\n");
      out.write("            $(\"#suggestion_box1 #submitbtn1,#suggestion_box1 .closeSuggestion\").click(function () {\r\n");
      out.write("                    \r\n");
      out.write("                var description = $(\"#suggestion_box1 #Description1\").val() + \"〖 手机号码：\" + 13213132610 + \",QQ号码:\" + 854529175 + \" 〗\";\r\n");
      out.write("        \r\n");
      out.write("                if ($(\"#suggestion_box1 #Description1\").val() != \"\" && $(\"#suggestion_box1 #Description1\").val() != undefined) {\r\n");
      out.write("                    $.post(\"/debtdeal/Negotiable/FeedBack\", { description: description, categoryId: \"131\" }, function (e) {\r\n");
      out.write("                        $(\".fankui_emsg\").html(e.Message);\r\n");
      out.write("                        $(\"#suggestion_box1 #Description1\").val(\"\"); //清空内容\r\n");
      out.write("                    });\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            $(\"#suggestion_box1 .closeSuggestion,#submitbtn1\").click(function () {\r\n");
      out.write("                $(\"#suggestion_box1,.cover\").hide();\r\n");
      out.write("            });\r\n");
      out.write("            $(\".userInfo_goOldVer\").click(function (e) {\r\n");
      out.write("                $(\"#cover,#suggestion_box1\").show();\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("\r\n");
      out.write("            });\r\n");
      out.write("            $('#vison').click(function () {\r\n");
      out.write("                switchvosion(1);\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    </SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT type=text/javascript>\r\n");
      out.write("        var polar = document.getElementById('polar');\r\n");
      out.write("        if (polar != null && polar != 'undefined') {\r\n");
      out.write("            var myChart = echarts.init(polar);\r\n");
      out.write("\r\n");
      out.write("            myChart.setOption({\r\n");
      out.write("                toolbox: {\r\n");
      out.write("                    show: false,\r\n");
      out.write("                    feature: {\r\n");
      out.write("                        mark: { show: true },\r\n");
      out.write("                        dataView: { show: true, readOnly: false },\r\n");
      out.write("                        restore: { show: true },\r\n");
      out.write("                        saveAsImage: { show: true }\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                calculable: false,\r\n");
      out.write("                polar: [\r\n");
      out.write("                    {\r\n");
      out.write("                        indicator: [\r\n");
      out.write("                            { text: '', max: 20 },\r\n");
      out.write("                            { text: '', max: 20 },\r\n");
      out.write("                            { text: '', max: 20 },\r\n");
      out.write("                            { text: '', max: 20 },\r\n");
      out.write("                            { text: '', max: 20 }\r\n");
      out.write("                        ],\r\n");
      out.write("                        radius: 90\r\n");
      out.write("                    }\r\n");
      out.write("                ],\r\n");
      out.write("                series: [\r\n");
      out.write("                    {\r\n");
      out.write("                        name: '',\r\n");
      out.write("                        type: 'radar',\r\n");
      out.write("                        itemStyle: {\r\n");
      out.write("                            normal: {\r\n");
      out.write("                                areaStyle: {\r\n");
      out.write("                                    type: 'default'\r\n");
      out.write("                                }\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        data: [\r\n");
      out.write("                            {\r\n");
      out.write("                                value: [0, 0, 0, 16, 0],\r\n");
      out.write("\r\n");
      out.write("                                name: ''\r\n");
      out.write("                            }\r\n");
      out.write("                        ]\r\n");
      out.write("                    }\r\n");
      out.write("                ]\r\n");
      out.write("            });\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("    </SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT>\r\n");
      out.write("        //切换新旧体验版\r\n");
      out.write("        function switchvosion(ver) {\r\n");
      out.write("            try {\r\n");
      out.write("                $.cookie('Borrow-version', ver, { expires: 30, path: '/', domain: 'loan.ppdai.com', secure: false });\r\n");
      out.write("                window.location.href = window.location.href;\r\n");
      out.write("            } catch (err) {\r\n");
      out.write("                //\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $(function () {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: \"/accountmessage?Type=3\",\r\n");
      out.write("                type: \"POST\",\r\n");
      out.write("                dataType: 'html',\r\n");
      out.write("                success: function (date) {\r\n");
      out.write("                    //alert(date);\r\n");
      out.write("                    if (date != '') {\r\n");
      out.write("                        //alert(date);\r\n");
      out.write("                        var remind = $('<div id=\"remindtips\"></div>');\r\n");
      out.write("                        $('body').prepend(remind);\r\n");
      out.write("                        remind.prepend($(date));\r\n");
      out.write("                        $('#remindtips>div').append('<span id=\"remindclose\"></span>');\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                },\r\n");
      out.write("                error: function (er) {\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            $('body').on('click', '#remindclose', function () {\r\n");
      out.write("                $(this).parents('#remindtips').remove();\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT>\r\n");
      out.write("        //var scaleMap = $(\"#scaleMap\");\r\n");
      out.write("        //if (scaleMap != null && scaleMap != 'undefined') {\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        //}\r\n");
      out.write("        $(\"#scaleMap\").css({ \"width\": 110, \"height\": 72 }).scaleMap({ scale: '1' });\r\n");
      out.write("        $(function () {\r\n");
      out.write("            if ($('.my-frame').width() == 1200) {\r\n");
      out.write("                $('.top_inner > .top_inner, .mainNav_inner').width(1188);\r\n");
      out.write("                $('.breadcrumb').width(1169);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    </SCRIPT>\r\n");
      out.write("<!--列表确认 开始--><!--列表确认 结束--><!--营销 开始--><!--营销 结束--><!--切换角色 开始--><!--切换角色 结束--><!--提额 开始--><!--提额 结束--><!--拍币 开始-->\r\n");
      out.write("<SCRIPT type=text/javascript>\r\n");
      out.write("        $(\"#btnGetPaiMoney\").click(function () {\r\n");
      out.write("            var $this = $(this);\r\n");
      out.write("            if ($this.attr(\"disabled\") == \"disabled\") return false;\r\n");
      out.write("            $this.attr(\"disabled\", true);\r\n");
      out.write("            if ($this.hasClass(\"signIn\")) {\r\n");
      out.write("                $this.removeClass(\"hover\");\r\n");
      out.write("            } else {\r\n");
      out.write("                $this.removeClass(\"my-ac-qdsignb\").addClass(\"my-ac-qdsigna\");\r\n");
      out.write("            }\r\n");
      out.write("            $this.removeClass(\"my-ac-qdsignb\").addClass(\"my-ac-qdsigna\");\r\n");
      out.write("            var gateway = new servicestack.ClientGateway('http://' + window.location.host);\r\n");
      out.write("            var data = {};\r\n");
      out.write("            gateway.postToService(\r\n");
      out.write("                {\r\n");
      out.write("                    PaiMoneyRequest: data\r\n");
      out.write("                }, function (e) {\r\n");
      out.write("                    $this.PPDfloatDiv({\r\n");
      out.write("                        floatbgtype: true,\r\n");
      out.write("                        handertext: '签到成功！',\r\n");
      out.write("                        context: \"<div style='font-size:14px'>\" + e.Message + \"</div>\",\r\n");
      out.write("                        floattruebtn: false,\r\n");
      out.write("                        floatfalsebtn: '确定',\r\n");
      out.write("                        btnshow: true,\r\n");
      out.write("                        keyboards: false\r\n");
      out.write("                    });\r\n");
      out.write("                    $(\"#signDay\").text(e.Day);\r\n");
      out.write("                    $(\"#paiMoney\").text(e.MoneyAll);\r\n");
      out.write("                    $this.text(\"已签\");\r\n");
      out.write("                    $(\".left_gray\").attr(\"title\", e.Message);\r\n");
      out.write("                    $(\".left_gray\").show();\r\n");
      out.write("                    $(\".left_yellow\").hide();\r\n");
      out.write("                }, function (e) {\r\n");
      out.write("                    $this.attr(\"disabled\", false);\r\n");
      out.write("                    $this.css({ color: \"#690\", cursor: \"pointer\" });\r\n");
      out.write("                    alert(\"您可能已经签到，请刷新后再试，或明天再来~\");\r\n");
      out.write("                }\r\n");
      out.write("            );\r\n");
      out.write("        });\r\n");
      out.write("    </SCRIPT>\r\n");
      out.write("<!--拍币 结束--><!--营销部分 开始-->\r\n");
      out.write("<SCRIPT type=text/javascript>\r\n");
      out.write("        $(document).ready(function () {\r\n");
      out.write("            var referUrl = 'http://loan.ppdai.com/firstborrow/createlist';\r\n");
      out.write("            if ('0' == '1' && referUrl.indexOf(\"firstuserdetail\") > 0) {\r\n");
      out.write("                var txt = \"拍拍贷销售专员稍后会与您联系。在此期间，您可以继续在网站自助操作，完成淘宝认证及上传资料。\";\r\n");
      out.write("                $('body').PPDfloatDiv({\r\n");
      out.write("                    floatbgtype: true,\r\n");
      out.write("                    handertext: '提示',\r\n");
      out.write("                    context: \"<div style='font-size:14px'>\" + txt + \"</div>\",\r\n");
      out.write("                    floattruebtn: false,\r\n");
      out.write("                    floatfalsebtn: '确定',\r\n");
      out.write("                    btnshow: true,\r\n");
      out.write("                    keyboards: false\r\n");
      out.write("                });\r\n");
      out.write("                $('#modalbackdroptrue').on('hide', function () {\r\n");
      out.write("                    window.location.href = \"/account/borrow\";\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("    </SCRIPT>\r\n");
      out.write("<!--营销部分 结束--><!--记录当前使用角色 开始-->\r\n");
      out.write("<SCRIPT type=text/javascript>\r\n");
      out.write("        $.cookie(\"ppdaiRole\", \"8\", { expires: 365, path: '/', domain: '.ppdai.com', secure: false });\r\n");
      out.write("    </SCRIPT>\r\n");
      out.write("<!--记录当前使用角色 结束--><!--交互 开始-->\r\n");
      out.write("<SCRIPT>\r\n");
      out.write("        $(\".my-hn-user\").bind(\"click\", function () {\r\n");
      out.write("            $(this).closest(\"tr\").next().toggleClass(\"dtr\");\r\n");
      out.write("        });\r\n");
      out.write("        $(\".close\").click(function () {\r\n");
      out.write("            $(this).parent().remove();\r\n");
      out.write("        });\r\n");
      out.write("    </SCRIPT>\r\n");
      out.write("<!---交互 结束--><!--topNav 提示 开始 -->\r\n");
      out.write("<SCRIPT src=\"CSS/topnav.js\"></SCRIPT>\r\n");
      out.write("<!--topNav 提示 开始 --><!-- Google Tag Manager --><NOSCRIPT><IFRAME \r\n");
      out.write("style=\"DISPLAY: none; VISIBILITY: hidden\" height=0 src=\"about:blank\" \r\n");
      out.write("width=0></IFRAME></NOSCRIPT>\r\n");
      out.write("<SCRIPT>(function (w, d, s, l, i) {\r\n");
      out.write("    w[l] = w[l] || []; w[l].push({\r\n");
      out.write("        'gtm.start':\r\n");
      out.write("            new Date().getTime(), event: 'gtm.js'\r\n");
      out.write("    }); var f = d.getElementsByTagName(s)[0],\r\n");
      out.write("            j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =\r\n");
      out.write("                '//www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);\r\n");
      out.write("})(window, document, 'script', 'dataLayer', 'GTM-PVQ5D8');</SCRIPT>\r\n");
      out.write("<!-- End Google Tag Manager --></BODY></HTML>\r\n");
      out.write("\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
