package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class updatePhone_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("   <title>绑定/修改手机</title>\r\n");
      out.write("<meta name=\"description\" content=\"拍拍贷，中国首家，最大、最多人使用的互联网金融P2P(人人贷)网络借贷平台。提供小额贷款,短期贷款,个人贷款,抵押,无抵押贷款服务。利率自定,借期灵活。您还可以成为借出人理财借贷投资，获得高年收益率回报，超低门槛，超高收益。作为可信赖的投融资,理财,贷款,信贷平台,拍拍贷助您财富实现增值\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"网络贷款,民间借贷,小额贷款,无抵押贷款,信用贷款,网络借贷,借贷平台,拍拍贷,人人贷,投资理财,个人理财,p2p贷款,贷款,互联网金融,投融资\" />\r\n");
      out.write("<link href=\"./ppd_updatePhone_files/basic.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"./ppd_updatePhone_files/layout.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"./ppd_updatePhone_files/account.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"./ppd_updatePhone_files/bindAccount.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"./ppd_updatePhone_files/validation.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!--头部-->\r\n");
      out.write("    <div class=\"PPD_header_nav\" style=\"margin-bottom: 0;\">\r\n");
      out.write("        <div class=\"PPD_login_status\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"mainNav\">\r\n");
      out.write("        <div class=\"mainNav_inner clearfix w1000center\">\r\n");
      out.write("            <h1 class=\"logo\">\r\n");
      out.write("                <a href=\"http://www.ppdai.com/\">\r\n");
      out.write("                    <img src=\"./ppd_updatePhone_files/logo.png\" alt=\"ppdai logo\" />\r\n");
      out.write("                </a>\r\n");
      out.write("            </h1>\r\n");
      out.write("            <ul id=\"tabIcon\">\r\n");
      out.write("                <li class=\"hasSubMenu\">\r\n");
      out.write("                    <a href=\"http://www.ppdai.com/lend\">我要投资</a>\r\n");
      out.write("                    <div class=\"subMenu\">\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/lend\">我要借出</a>\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/product/list\">彩虹计划</a>\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/debtdeal/AlldebtList/DebtList\">如何借出</a>\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/help/principalprotection\">本金保障</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"hasSubMenu\">\r\n");
      out.write("                    <a href=\"http://www.ppdai.com/borrow\">我要借款</a>\r\n");
      out.write("                    <div class=\"subMenu\">\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/borrow\">我要借入</a>\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/help/howtoborrow.html\">如何借入</a>\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/borrow/interestcalculate\">利息计算器</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"hasSubMenu\">\r\n");
      out.write("                    <a href=\"myAccount-baccount\" class=\"tabon\">我的账户</a>\r\n");
      out.write("                    <div class=\"subMenu\">\r\n");
      out.write("                        <a href=\"myAccount-baccount\">借款账户</a>\r\n");
      out.write("                        <a href=\"myAccount-laccount\">投资账户</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"hasSubMenu\">\r\n");
      out.write("                    <a href=\"http://www.ppdai.com/help/aboutus\">关于拍拍贷</a>\r\n");
      out.write("                    <div class=\"subMenu\">\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/help/aboutus\">关于我们</a>\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/help/howworks\">工作原理</a>\r\n");
      out.write("                        <a href=\"http://www.ppdai.com/help/fees\">资费说明</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--头部结束-->\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"main\" style=\"padding-top: 10px;margin-bottom: 20px;\">\r\n");
      out.write("    <div class=\"my-frame\">\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("    <ul class=\"breadcrumb\" style=\"border: none !important;\">\r\n");
      out.write("                    <li><a href=\"/\">首页</a> <span class=\"divider\">></span></li>\r\n");
      out.write("                            <li><a href=\"myAccount-baccount\">我的账户-我是借入者</a> <span class=\"divider\">></span></li>\r\n");
      out.write("                        <li class=\"active\">绑定/修改手机</li>\r\n");
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"clearfix\">\r\n");
      out.write("            <!-- Left Nav -->\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"my-f-left fl\">\r\n");
      out.write("    <div class=\"my-f-l-nav\">我的账户</div>\r\n");
      out.write("    <ul class=\"my-f-l-list\">\r\n");
      out.write("            <li><a href=\"myAccount-laccount\">我的账户首页</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <div class=\"my-f-l-nav\">资金管理</div>\r\n");
      out.write("    <ul class=\"my-f-l-list\">\r\n");
      out.write("        <li><a href=\"myAccount-moneyhistory?classType=99&dateType=3\">资金记录</a></li>\r\n");
      out.write("        <li><a href=\"recharge.jsp\">充值</a></li>\r\n");
      out.write("        <li><a href=\"withdrawCash.jsp\">提现</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("        <div class=\"my-f-l-nav\">投资管理</div>\r\n");
      out.write("        <ul class=\"my-f-l-list\">\r\n");
      out.write("            <li><a href=\"myAccount-investMessage?classType=99&dateType=3\">投资列表</a></li>\r\n");
      out.write("            <li><a href=\"http://www.ppdai.com/autobid/addrule\">自动投标</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    <div class=\"my-f-l-nav\">账户设置</div>\r\n");
      out.write("    <ul class=\"my-f-l-list\">\r\n");
      out.write("        <li><a href=\"myAccount-securityCenter\" class=\"on\">安全中心</a></li>\r\n");
      out.write("        <li><a href=\"myAccount-connectNumber\" class=\"\">关联账户</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Right -->\r\n");
      out.write("            <div class=\"ml20 my-f-right fl\">\r\n");
      out.write("                <div class=\"my-f-r-safty\">\r\n");
      out.write("                    <div class=\"my-f-r-sf-title c666\">修改手机</div>\r\n");
      out.write("                        <div class=\"my-f-r-sf-degree mt5 bgfafafa\">您已绑定的手机：<span class=\"cf7971a\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${safety.tel}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("</span></div>\r\n");
      out.write("                        <div class=\"p10 \">\r\n");
      out.write("                        \r\n");
      out.write("                            <div class=\"my-f-r-sf-bindStyle\">通过【原手机号】+【短信验证码】修改手机号</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"my-f-r-wrapForm\" style=\"\">\r\n");
      out.write("                            <form action=\"myAccount-upuserPhone\" method=\"POST\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"Step\" value=\"OldValidate\" />\r\n");
      out.write("                                    <input type=\"hidden\" name=\"Way\" value=\"Mobile\" />\r\n");
      out.write("                                    <ul class=\"formItem pl188 pt36\">\r\n");
      out.write("                                        <li class=\"clearfix\">\r\n");
      out.write("                                            <label class=\"w80\">原手机号：</label>\r\n");
      out.write("                                            <input type=\"text\" class=\"w246 bd\" id=\"txtMobile\" name=\"Mobile\" maxlength=\"11\" data-validation-engine=\"validate[required,custom[mobile]]\" />\r\n");
      out.write("          \r\n");
      out.write("                                            <div class=\"formErrorMsg\"></div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"clearfix\">\r\n");
      out.write("                                            <label class=\"w80\">验证码：</label>\r\n");
      out.write("                                            <input type=\"text\" class=\"w123 bd\" name=\"ValidateCode\" maxlength=\"6\" data-validation-engine=\"validate[required]\" />\r\n");
      out.write("                                            <input type=\"button\" value=\"获取验证码\" class=\"getmobilevalidata w114\" data-step=\"OldValidate\" data-way=\"Mobile\" />\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"clearfix\">\r\n");
      out.write("                                            <label class=\"w80\">新手机号：</label>\r\n");
      out.write("                                            <input type=\"text\" class=\"w246 bd\" id=\"newPhone\" name=\"newPhone\" maxlength=\"11\" data-validation-engine=\"validate[required,custom[mobile]]\" />\r\n");
      out.write("          \r\n");
      out.write("                                            <div class=\"formErrorMsg\"></div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <div class=\"my-f-r-submit pl268 pb30 pt11\"><input type=\"submit\" value=\"提交\" class=\"submitBtn\" /></div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"formExplain\">\r\n");
      out.write("                            温馨提示：若无法通过以上方式修改，请联系 <a href=\"http://wpa.b.qq.com/cgi/wpa.php?ln=1&key=XzgwMDAyNzUzNV8xODAzNjBfODAwMDI3NTM1XzJf\" target=\"_blank\">在线客服</a> 。</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<input type=\"hidden\" id=\"hid_code\" value=\"0\" />\r\n");
      out.write("<input type=\"hidden\" id=\"hid_message\" value=\"\" />\r\n");
      out.write("<input type=\"hidden\" id=\"hid_step\" value=\"OldValidate\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--底部-->\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("    <div class=\"footer_footerBottom\">\r\n");
      out.write("        <ul class=\"footer_footerBottomNav clearfix\">\r\n");
      out.write("            <li><span class=\"webindex\"></span><a href=\"http://www.ppdai.com/\">网站首页</a>|</li>\r\n");
      out.write("            <li><span class=\"aboutus\"></span><a href=\"http://www.ppdai.com/help/aboutus\">关于我们</a>|</li>\r\n");
      out.write("            <li><span class=\"mapsite\"></span><a href=\"http://www.ppdai.com/home/sitemap\">网站地图</a>|</li>\r\n");
      out.write("            <li><span class=\"webservice\"></span><a href=\"http://www.ppdai.com/consult\">客服中心</a>|</li>\r\n");
      out.write("            <li class=\"nomr\"><span class=\"onlneserve\"></span><a href=\"http://wpa.b.qq.com/cgi/wpa.php?ln=1&key=XzgwMDAyNzUzNV8xODAzNjBfODAwMDI3NTM1XzJf\" target=\"_blank\">在线咨询</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <p>Copyright Reserved 2007-2015©拍拍贷（www.ppdai.com）&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;沪ICP备05063398号&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;上海拍拍贷金融信息服务有限公司</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--底部结束-->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./ppd_updatePhone_files/jquery.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script src=\"http://ac.ppdai.com/status?v=2014\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script src=\"./ppd_updatePhone_files/init.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        $(function () {\r\n");
      out.write("            $(\".my-f-l-list li a.on\").closest(\".my-f-l-list\").prev(\".my-f-l-nav\").addClass(\"my-f-l-nav-sd\");\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("<script src=\"http://ac.ppdaicdn.com/js/jquery.cookie.min.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("<script src=\"./ppd_updatePhone_files/ppd_ac_utils.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("<script src=\"./ppd_updatePhone_files/validation.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("<script src=\"./ppd_updatePhone_files/validation-zh.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function () {\r\n");
      out.write("    var acUtils = new PPDAcUtils(\"v1.0\");\r\n");
      out.write("\r\n");
      out.write("    var step = $('#hid_step').val();\r\n");
      out.write("    var way1 = 'Email',\r\n");
      out.write("        way2 = 'Mobile';\r\n");
      out.write("    var remainTimeKey0 = step + '_bindmobile_remainTime',\r\n");
      out.write("        remainTimeKey1 = step + way1 + '_bindmobile_remainTime',\r\n");
      out.write("        remainTimeKey2 = step + way2 + '_bindmobile_remainTime';\r\n");
      out.write("    var cookieObj = { expires: 1 / 24 / 60, path: '/', domain: '.ac.ppdai.com', secure: false };\r\n");
      out.write("\r\n");
      out.write("    function checkRemainTime(obj, remainTimeKey) {\r\n");
      out.write("        if (jQuery.cookie(remainTimeKey) && jQuery.cookie(remainTimeKey).length > 0) {\r\n");
      out.write("            acUtils.remainTime(obj, jQuery.cookie(remainTimeKey), null, '秒后重新发送', remainTimeKey, cookieObj);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    function init() {\r\n");
      out.write("        if ($('.getemailvalidata').length > 0) {\r\n");
      out.write("            if ($('.getemailvalidata').data('step') == 'Add') {\r\n");
      out.write("                checkRemainTime('.getemailvalidata', remainTimeKey0);\r\n");
      out.write("            } else if ($('.getemailvalidata').data('way') == 'Email') {\r\n");
      out.write("                checkRemainTime('.getemailvalidata', remainTimeKey1);\r\n");
      out.write("            } else if ($('.getemailvalidata').data('way') == 'Mobile') {\r\n");
      out.write("                checkRemainTime('.getemailvalidata', remainTimeKey2);\r\n");
      out.write("            } else {\r\n");
      out.write("                //\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        if ($('.getmobilevalidata').length > 0) {\r\n");
      out.write("            if ($('.getmobilevalidata').data('step') == 'Add') {\r\n");
      out.write("                checkRemainTime('.getmobilevalidata', remainTimeKey0);\r\n");
      out.write("            } else if ($('.getmobilevalidata').data('way') == 'Email') {\r\n");
      out.write("                checkRemainTime('.getmobilevalidata', remainTimeKey1);\r\n");
      out.write("            } else if ($('.getmobilevalidata').data('way') == 'Mobile') {\r\n");
      out.write("                checkRemainTime('.getmobilevalidata', remainTimeKey2);\r\n");
      out.write("            } else {\r\n");
      out.write("                //\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    setTimeout(init, 10);\r\n");
      out.write("\r\n");
      out.write("    $('.my-f-r-sf-bindStyle').click(function () {\r\n");
      out.write("        if ($(this).children('a').text() == '点击修改') {\r\n");
      out.write("            $(this).parent().next('.my-f-r-wrapForm').slideDown().siblings('.my-f-r-wrapForm').slideUp();\r\n");
      out.write("            $('.my-f-r-sf-bindStyle>a').text('点击修改');\r\n");
      out.write("            $(this).children('a').text('点击收起');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $(\"form\").validationEngine();\r\n");
      out.write("\r\n");
      out.write("    //手机验证码\r\n");
      out.write("    $('.getmobilevalidata').click(function () {\r\n");
      out.write("        var $this = $(this);\r\n");
      out.write("        var regphone = /^(13[0-9]|14[57]|15[0-35-9]|17[0678]|18[0-9])[0-9]{8}$/,\r\n");
      out.write("            mobilephone = $('#txtMobile');\r\n");
      out.write("        if ($.trim(mobilephone.val()) == '') {\r\n");
      out.write("            mobilephone.parent().children('.formErrorMsg').html('手机号码不能为空').show();\r\n");
      out.write("        } else if (mobilephone.val().length != 11 || !regphone.test(mobilephone.val())) {\r\n");
      out.write("            mobilephone.parent().children('.formErrorMsg').html('请输入正确的手机号码').show();\r\n");
      out.write("        } else {\r\n");
      out.write("            mobilephone.parent().children('.formErrorMsg').hide();\r\n");
      out.write("\r\n");
      out.write("            if ($this.data('step') == 'Add') {\r\n");
      out.write("                acUtils.remainTime($this, 60, null, '秒后重新发送', remainTimeKey0, cookieObj);\r\n");
      out.write("            } else if ($this.data('way') == 'Email') {\r\n");
      out.write("                acUtils.remainTime($this, 60, null, '秒后重新发送', remainTimeKey1, cookieObj);\r\n");
      out.write("            } else if ($this.data('way') == 'Mobile') {\r\n");
      out.write("                acUtils.remainTime($this, 60, null, '秒后重新发送', remainTimeKey2, cookieObj);\r\n");
      out.write("            } else {\r\n");
      out.write("                //\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            var mobile = mobilephone.val();\r\n");
      out.write("            var datastep = $(this).data(\"step\") || \"\";\r\n");
      out.write("            var sendFor = 'UpdateMobilePhone';\r\n");
      out.write("            $.post(\"/userbind/sendsmsvalidatecode\", { mobile: mobile, step: datastep, sendFor: sendFor }, function (res) {\r\n");
      out.write("                if (res != null) {\r\n");
      out.write("                    if (res.Code == 0) {\r\n");
      out.write("                        //$(this).attr(\"disabled\", false);\r\n");
      out.write("                        alert(res.Message);\r\n");
      out.write("                    } else {\r\n");
      out.write("                        alert(res.Message);\r\n");
      out.write("                        //remainTime($(this));\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    var page_message = $('#hid_message').val();\r\n");
      out.write("    //var page_code = $('hide_code').val();\r\n");
      out.write("    if (page_message && page_message.length > 0) {\r\n");
      out.write("        alert(page_message);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    $('.my-f-r-sf-bindStyle').click();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Tag Manager -->\r\n");
      out.write("    <noscript>\r\n");
      out.write("        <iframe src=\"//www.googletagmanager.com/ns.html?id=GTM-PVQ5D8\"\r\n");
      out.write("            height=\"0\" width=\"0\" style=\"display: none; visibility: hidden\"></iframe>\r\n");
      out.write("    </noscript>\r\n");
      out.write("    <script>(function (w, d, s, l, i) {\r\n");
      out.write("    w[l] = w[l] || []; w[l].push({\r\n");
      out.write("        'gtm.start':\r\n");
      out.write("            new Date().getTime(), event: 'gtm.js'\r\n");
      out.write("    }); var f = d.getElementsByTagName(s)[0],\r\n");
      out.write("            j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =\r\n");
      out.write("                './ppd_updatePhone_files/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);\r\n");
      out.write("})(window, document, 'script', 'dataLayer', 'GTM-PVQ5D8');</script>\r\n");
      out.write("<!-- End Google Tag Manager -->\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        var _bdhmProtocol = ((\"https:\" == document.location.protocol) ? \" https://\" : \" http://\");\r\n");
      out.write("        document.write(unescape(\"%3Cscript src='\" + _bdhmProtocol + \"hm.baidu.com/h.js%3Fcfc74b94210e27ea643566ddece504a7' type='text/javascript'%3E%3C/script%3E\"));\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
